### PR TITLE
fix(cli): Do not bundle test files

### LINKED ISSUE #6634: [DISCORD:1402669147023740958] Test files inside /tools/ folder are bundled (MacOS, on Windows it doesn't crash the Mastra server)
This issue was created from Discord post: https://discord.com/channels/1309558646228779139/1402669147023740958

Is there way to manage bundler configuration to exclude `src/**/*.test.ts` files?

### PR DESCRIPTION
**Pull request by LekoArts**
## Description

Similarly to https://github.com/mastra-ai/mastra/pull/5125 this PR updates the `globby` pattern we use for deciding what tools to bundle. `globby` accepts a `string | string[]` and so far we only passed a `string` to it.

So in this PR I mainly did two things to exclude test files from bundling:
- Adjust our default tools glob from a string to an array to include the negation of test files
- Adjust function signature types for `getToolsInputOptions()` and where it was used to allow for `(string | string[])[]` now (this means each element can be either a string or an array of strings)

So the type changes are backwards-compatible as they only extend the allowed type.

## Related Issue(s)

Fixes https://github.com/mastra-ai/mastra/issues/6634

## Type of Change

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Code refactoring
- [ ] Performance improvement
- [ ] Test update

## Checklist

- [x] I have made corresponding changes to the documentation (if applicable)
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: packages/deployer/src/bundler/index.ts [hunk 1]
```diff
@@ -196,7 +196,7 @@ export abstract class Bundler extends MastraBundler {
     return inputOptions;
   }
 
-  async getToolsInputOptions(toolsPaths: string[]) {
+  async getToolsInputOptions(toolsPaths: (string | string[])[]) {
```
Comment (LekoArts) [inline packages/deployer/src/bundler/index.ts:199]: Now the `toolPath` passed to `globby` will be our default array to negate the test files

**Review by wardpeet — COMMENTED** [review]
What's the reason for changing the type and not keep it as an array?

**Comment by LekoArts** [comment]
I understood the function `getToolsInputOptions` like so:

```ts
for (const toolPath of toolsPaths) {
      const expandedPaths = await globby(toolPath, {});
```

If we'd keep the `string[]` type we'd need to pass in `['tools/**/*.{js,ts}', '!tools/**/*.test.ts', ...userDefinedTools]` to the function. So `globby` will call them separately in the for loop. This way the `!` negation won't have an effect. It only works if we pass in `[['tools/**/*.{js,ts}', '!tools/**/*.test.ts'], ...userDefinedTools]]`.

So with our initial default glob for getting the tool files we'll also want to pass in the negation as separate globby calls won't do what we need.

**Comment by wardpeet** [comment]
My bad i didn't see the nested [] `(string | string[])[])`

**Review by wardpeet — APPROVED** [review]

**Comment by genaby** [comment]
Sorry that I used this thread context to share feedback as a Mastra user.

I pretty sure you had these ideas already, but I think it still would be nice to be said by a user of your wonderful framework.

Technically Mastra can expose the tools rest api directly for simple usage in custom applications which interacts with Mastra.  Now it is still possible via mcp server and agenets rest api (BTW: the last one shows 404 for registered tools)

But current version of openapi doesn't include tools in/out zod schemas so technically it is `POST /api/agent/{toolId}/execute` with untyped request body and response. Which I have to say still is not a problem since developer can share zod schema between tool and ui code.

Ideally Mastra can handle web apps too in one ecosystem 🤯  (even with server rendering), so tool calling from a front-end can be even simpler.

it would be the stack/framework of my dream (and I hope for many Mastra users too): where I can create branded ui application(s), yep not all tools are for agents, some of them are just for specific ui apps needs so i can add @mastra/rest-... and expose what I need, single place for auth, monitoring, and etc. - single framework to rule them all, simple deployment.
