### PR TITLE
fix(@mastra/core): apply output processors before saving to memory

### LINKED ISSUE #7087: [BUG] Memory unaffected by Agent Output Processors
### Describe the Bug

When adding an Output Processor to an agent, you are able to modify or filter the output of the response before it goes to the user. For example, if you modified the text of the result, you can see the changed result return to the UI as expected. 

In a situation where you are loading the previous messages from the thread and displaying them to a user, all you have to do is hit refresh, and you'll see the original unmodified text of the result. 

The expectation is that any changes made via an Output Processor would propagate into the memory database itself. 

Especially when an Output Processor is being used to redact or remove PII or other sensitive material, this is a major oversight. 

### Steps To Reproduce

In a mastra project, create a new Output Processor that for demo purposes, removes the response text completely:

```
import type { Processor } from "@mastra/core/processors";
import type { ChunkType } from "@mastra/core";

export class MetadataProcessor implements Processor {
  readonly name = "metadata-processor";

  constructor() {}

  async processOutputStream({
    part,
    streamParts,
    state,
    abort,
  }: {
    part: ChunkType;
    streamParts: ChunkType[];
    state: Record<string, any>;
    abort: (reason?: string) => never;
  }): Promise<ChunkType | null | undefined> {
    if (part.type === "text-delta") {
      return null;
    }

    return part; // Emit the part
  }
}
```

Add that to your agent:
```
export const myAgent = new Agent({
  {...}
  outputProcessors: [new MetadataProcessor()],
});
```

Next, use generate or stream or streamVNext to generate a response. You'll see a response without any text. Be sure to set a threadId and resourceId
```
agent.streamVNext('hi there', {
   format: "aisdk",
   memory:  {
      thread: 'thread-id-here',
      resource: 'resource-id-here'
   }
}
```

Finally, get all the messages from the thread:
```
const storage = mastra.getStorage();
const messages =
    (await storage?.getMessages({
      threadId: 'thread-id-here',
      format: "v2",
    })) || [];

console.log(messages);
```
In the above, you'll see the the unmodified original message content as if the Output Processor never ran
```

### Expected Behavior

If we are modifying the output before it returns to the user, we'd want to ensure that the message's content retains that modification beyond the initial request-- so those changes should propagate into the database.

### Environment Information

- Mastra Version: 0.14.1

### Verification

- [x] I have searched the existing issues to make sure this is not a duplicate
- [x] I have included sufficient information for the team to reproduce and understand the issue

### PR DESCRIPTION
**Pull request by TylerBarnes**
Fixes #7087

Output processors were modifying the streamed response but the original unmodified text was still being saved to memory. This was particularly problematic for PII redaction use cases.

The fix moves output processor application earlier in the stream pipeline, ensuring transformations happen before messages are persisted to storage.

Before this fix, if you had a processor that redacted sensitive data:
```typescript
class RedactionProcessor implements Processor {
  async processOutputStream({ part }) {
    if (part.type === 'text-delta' && part.text) {
      return { ...part, text: part.text.replace(/SSN-\d{3}-\d{2}-\d{4}/g, '[REDACTED]') };
    }
    return part;
  }
}
```

The user would see `[REDACTED]` in the stream, but refreshing the page would show the original SSN from memory.

Now the processor runs before memory storage, so both the stream and stored messages show `[REDACTED]` consistently.

### CODE REVIEW

File: packages/core/src/agent/index.ts [hunk 1]
```diff
@@ -279,6 +279,22 @@ export class Agent<
...
+  private async getResolvedOutputProcessors(runtimeContext?: RuntimeContext): Promise<OutputProcessor[]> {
+    if (!this.#outputProcessors) {
+      return [];
+    }
+
+    if (typeof this.#outputProcessors === 'function') {
+      if (!runtimeContext) {
+        // Create a default runtime context if none provided
+        return [];
+      }
```
Comment (DanielSLew) [inline packages/core/src/agent/index.ts]: The comment contradicts what the code is doing, don't we want to return the output processors even if there's no runtime context

File: packages/core/src/stream/base/output.ts [hunk 2]
```diff
@@ -560,41 +602,10 @@ export class MastraModelOutput<OUTPUT extends OutputSchema = undefined> extends
 
     let fullStream = this.teeStream();
 
-    const processorStates = new Map<string, ProcessorState>();
+    // Output processors are now applied in the baseStream transform
+    // so we don't need to apply them here anymore
```
Comment (DanielSLew) [inline packages/core/src/stream/base/output.ts]:
```suggestion
```

File: packages/core/src/loop/loop.ts [hunk 3]
```diff
@@ -110,7 +110,8 @@ export function loop<Tools extends ToolSet = ToolSet, OUTPUT extends OutputSchem
       onStepFinish: rest.options?.onStepFinish,
       includeRawChunks: !!includeRawChunks,
       output: rest.output,
-      outputProcessors,
+      // Don't pass outputProcessors here - they're applied in the inner MastraModelOutput
+      // created in llm-execution.ts to avoid double processing
```
Comment (NikAiyer) [inline packages/core/src/loop/loop.ts]: Do we need this comment?

File: packages/core/src/stream/base/output.ts (hunk 2 above)
Comment (NikAiyer) [inline packages/core/src/stream/base/output.ts]: Probably can remove this

File: packages/core/src/loop/loop.ts (hunk 3 above)
Comment (DanielSLew) [inline packages/core/src/loop/loop.ts]:
```suggestion
```

**Review by DanielSLew — APPROVED** [review]

File: packages/core/src/agent/index.ts (hunk 1 above)
Comment (TylerBarnes) [reply packages/core/src/agent/index.ts]: good catch, yeah this looks weird

**Review by NikAiyer — APPROVED** [review]

File: packages/core/src/loop/loop.ts (hunk 3 above)
Comment (TylerBarnes) [reply packages/core/src/loop/loop.ts]: Added this here intentionally since we initialize MastraModelOutput in multiple places, wanted to leavea note on why we don't do output processing in this place anymore and where it does happen instead

**Review by CalebBarnes — APPROVED** [review]

File: packages/core/src/loop/loop.ts (hunk 3 above)
Comment (TylerBarnes) [reply packages/core/src/loop/loop.ts]: yeah, wanted to leave a note for the future https://github.com/mastra-ai/mastra/pull/7647/files/9e04c49b9de4e54f9e2e7fc5ce443fd2af7718a3#r2334682806
