### PR TITLE
Provide fallback for extracted mastra options during bundling

### LINKED ISSUE #4822: [BUG] Mastra CLI telemetry-config.mjs empty file causing SyntaxError in mastra dev
# Bug Report

## Environment
- **Mastra version**: `^0.10.3`
- **Node.js version**: `v22.11.0`
- **OS**: macOS (Darwin 24.4.0)
- **Package manager**: yarn v1.22.22

## Bug Description
When running `mastra dev`, the CLI fails with a SyntaxError because the generated `telemetry-config.mjs` file is empty but the `instrumentation.mjs` file tries to import a named export `telemetry` from it.

## Error Output
```
$ mastra dev
INFO [2025-06-09 17:06:54.926 +0530] (Mastra CLI): [Mastra Dev] - Starting server...
file:///Users/karanjanthe/workspace/tezi-fast/apps/server/.mastra/output/instrumentation.mjs:14
import { telemetry } from './telemetry-config.mjs';
         ^^^^^^^^^
SyntaxError: The requested module './telemetry-config.mjs' does not provide an export named 'telemetry'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:177:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:260:5)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:543:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:111:9)

Node.js v22.11.0
ERROR [2025-06-09 17:06:58.438 +0530] (Mastra CLI): Attempting to restart server after error... (Attempt 1/3)
```

## Steps to Reproduce
1. Install Mastra `^0.10.3` in a project
2. Create basic Mastra configuration with agents
3. Run `mastra dev`
4. Error occurs immediately on startup

## File Analysis
The generated `.mastra/output/telemetry-config.mjs` file is completely empty (0 bytes), but `instrumentation.mjs` line 14 expects it to export a named `telemetry` export:

```javascript
import { telemetry } from './telemetry-config.mjs';
```

## Expected Behavior
- `mastra dev` should start successfully
- `telemetry-config.mjs` should either contain proper exports or the import should be conditional/optional

## Workaround
None found - this completely blocks usage of `mastra dev`.

## Additional Context
This appears to be a code generation issue where the CLI generates an empty telemetry config file but the instrumentation code assumes it contains exports. This might be related to the OpenTelemetry configuration setup.

## Project Structure
```
src/
  mastra/
    index.ts  # exports Mastra instance
  config/
    mastra.config.ts  # contains agent definitions
```

The project uses:
- @mastra/core: ^0.10.3
- @ai-sdk/openai: ^1.3.22  
- TypeScript with ESM modules

### PR DESCRIPTION
**Pull request by TheIsrael1**
- **Provide fallback for extracted mastra options during bundling**
- **changeset**

## Related Issue(s)
Fixes #4822

## Type of Change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Code refactoring
- [ ] Performance improvement
- [ ] Test update

## Checklist

- [ ] I have made corresponding changes to the documentation (if applicable)
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: packages/deployer/src/build/babel/remove-all-options-except.ts [hunk 1]
```diff
@@ -70,6 +72,27 @@ export function removeAllOptionsFromMastraExcept(
...
+      Program: {
+        exit(path) {
+          // Add a fallback export if no mastra configuration was found
+          const hasExport = path.node.body.some(
+            node => node.type === 'ExportNamedDeclaration' || node.type === 'ExportDefaultDeclaration',
+          );
+
+          if (!hasExport) {
+            if (logger) {
+              logger.warn(`Mastra ${option} config could not be extracted`);
```
Comment (wardpeet) [inline packages/deployer/src/build/babel/remove-all-options-except.ts]:
```suggestion
              logger.warn(`Mastra ${option} config could not be extracted. Makse sure you entry file looks like
export const mastra = new Mastra({
  ${option}: <value>
})

`);
```

**Review by wardpeet — APPROVED** [review]
This is so good! Added extra info to the error message
