### PR TITLE
fix(netlify-deployer): Instruct Netlify to use pre-bundled files

### LINKED ISSUE #10400: [BUG] Netlify Deploy does not work
### Describe the Bug

The deploy does not work as expected.

### Steps To Reproduce

1. Create a new project with `bun create mastra@latest`
2. Add netlify deployer (https://mastra.ai/docs/deployment/cloud-providers/netlify-deployer)
3. Deploy to netlify
4. Get this error:
```
Nov 21, 12:51:46 PM: c0b55160 ERROR  Invoke Error 	{"errorType":"TypeError","errorMessage":"y is not a function","stack":["TypeError: y is not a function","    at file:///var/task/___netlify-bootstrap.mjs:2:147388","    at AsyncLocalStorage.run (node:internal/async_local_storage/async_hooks:91:14)","    at Wd (file:///var/task/___netlify-bootstrap.mjs:2:147378)","    at async Runtime.handler (file:///var/task/___netlify-bootstrap.mjs:2:146608)","    at async Runtime.handleOnceStreaming (file:///var/runtime/index.mjs:1348:26)"]}Nov 21, 12:51:46 PM: c0b55160 Duration: 332.46 ms	Memory Usage: 198 MB
```

### Link to Minimal Reproducible Example

https://github.com/UltiRequiem/mastra-netlify-basic-setup

### Expected Behavior

The deployment does work.

### Environment Information

  System:
    OS: macOS 15.6.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 306.30 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 24.8.0 - /Users/eliazbobadilla/.nvm/versions/node/v24.8.0/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 11.6.0 - /Users/eliazbobadilla/.nvm/versions/node/v24.8.0/bin/npm
    pnpm: 10.16.0 - /opt/homebrew/bin/pnpm
    bun: 1.2.11 - /Users/eliazbobadilla/.bun/bin/bun
    Deno: 2.4.5 - /opt/homebrew/bin/deno
  Browsers:
    Brave Browser: 141.1.83.120
    Chrome: 142.0.7444.176
    Firefox: 141.0.3
    Safari: 18.6
  npmPackages:
    @mastra/core: ^0.24.5 => 0.24.5
    @mastra/deployer-netlify: ^0.13.22 => 0.13.22
    @mastra/evals: ^0.14.4 => 0.14.4
    @mastra/libsql: ^0.16.2 => 0.16.2
    @mastra/loggers: ^0.10.19 => 0.10.19
    @mastra/memory: ^0.15.11 => 0.15.11
    @types/bun: latest => 1.3.2
    @types/node: ^24.10.1 => 24.10.1
    mastra: ^0.18.5 => 0.18.5
    zod: ^4 => 4.1.12
  npmGlobalPackages:
    corepack: 0.34.0
    npm: 11.6.0
LLM Provide: open ai

### Verification

- [x] I have searched the existing issues to make sure this is not a duplicate
- [x] I have included sufficient information for the team to reproduce and understand the issue

### PR DESCRIPTION
**Pull request by UltiRequiem**
## Description

Adjust the generated `.netlify/v1/config.json` file to not let Netlify bundle the functions (since Mastra already bundles its output). Also, re-enable ESM shimming.

## Related Issue(s)

  Fixes #10400 

## Checklist

  - I have made corresponding changes to the documentation (if applicable)
  - I have added tests that prove my fix is effective or that my feature works

## Summary by CodeRabbit

* **New Features**
  * Netlify deployer now supports zero-argument initialization and emits a Netlify Frameworks API JSON config, adopting a .netlify/v1 layout for simpler automated deployments.

* **Documentation**
  * Updated guides and examples to reflect the Frameworks API config, new project layout, runtime env handling, and refined usage snippets.

* **Chores**
  * Added a patch changeset to adjust function bundling behavior and re-enable ESM shimming.

* **Bug Fixes**
  * Lint now detects LibSQL usage and aborts to prevent unsupported deployments.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

**Comment by graysonhicks** [comment]
Awesome, thanks @UltiRequiem! A couple things:
- make those settings overridable (e.g. not everyone wants `bun run build` as their build command).  let's default to `npm run build`
- we want to honor an existing netlify.toml
- don't need the `functions` in the toml file, they can be added to the existing `config.json` writing in the deploy
- can add `[build.environment]` as an option
- add some docs on this to the Netlify deployer

**Comment by crydafan** [comment]
go Eliaz, go!

File: deployers/netlify/src/index.ts [hunk 1]
```diff
@@ -56,6 +116,8 @@ export class NetlifyDeployer extends Deployer {
       ],
     });
```
Comment (graysonhicks) [inline deployers/netlify/src/index.ts:65]: Let's add the `functions` config here:

```
    // Use Netlify Frameworks API config.json
    // https://docs.netlify.com/build/frameworks/frameworks-api/
    await writeJson(join(outputDirectory, '.netlify', 'v1', 'config.json'), {
      functions: {
        directory: '.netlify/v1/functions',
        node_bundler: 'none', // Mastra pre-bundles, don't re-bundle
        included_files: ['.netlify/v1/functions/**'],
      },
      redirects: [
        {
          force: true,
          from: '/*',
          to: '/.netlify/functions/api/:splat',
          status: 200,
        },
      ],
    });
    ```

File: deployers/netlify/src/index.ts [hunk 2]
```diff
@@ -32,6 +61,37 @@ export class NetlifyDeployer extends Deployer {
...
+      netlifyTomlContent += '\n\n[build.environment]';
+
+      for (const [key, value] of Object.entries(this.buildConfig.environment)) {
+        netlifyTomlContent += `\n  ${key} = "${value}"`;
+      }
+    }
+
+    netlifyTomlContent += `
+
+[[redirects]]
```
Comment (graysonhicks) [inline deployers/netlify/src/index.ts]: I think redirects is already handled in the `config.json` generation in `writeJson`

File: deployers/netlify/src/index.ts (hunk 1 above)
Comment (UltiRequiem) [reply deployers/netlify/src/index.ts:65]: 😮 I think that was exactly what was needed.

File: deployers/netlify/src/index.ts (hunk 2 above)
Comment (UltiRequiem) [reply deployers/netlify/src/index.ts]: Got it

**Comment by LekoArts** [comment]
I made some updates to the PR so it's accurate and only includes the changes to the json file. I had some troubles testing this locally with `netlify dev` / `netlify build` + `netlify serve` so ideally we test this end-to-end with a published version.

**Comment by UltiRequiem** [comment]
@LekoArts why did you deleted the lint?

**Comment by LekoArts** [comment]
@UltiRequiem I'm not 100% sure that it was accurate since I couldn't find any evidence for that. Did you test the snapshot version out?

**Review by graysonhicks — APPROVED** [review]
