### PR TITLE
fix network-data by writing the steps in the correct format

### LINKED ISSUE #10238: how to access sub-agent tool results using ai sdk.
This issue was created from Discord post 1440455203835871302:

[Open in Discord](https://discord.com/channels/1309558646228779139/1440455203835871302)

Hi,
We have several agents whose tool results (structured outputs) are displayed on the frontend as intermediate steps. We’re now building a mega-agent that orchestrates these agents and should continue to surface their tool results in the UI. However, the AI SDK stream transformer is dropping those tool results. It currently only forwards data-* custom events from sub-agents, which prevents the tool outputs from coming through.  Here are the sub-agent level events (https://mastra.ai/docs/agents/networks#agent-output) and wondering if there is any way of getting access to them. (I am open to writing a custom transformer for the time being)

### PR DESCRIPTION
**Pull request by wardpeet**
Add support for better data-network structure. Each step is the result of the sub agent,workflow or agent with all necessary tools involved.

Fixes https://github.com/mastra-ai/mastra/issues/10238

## Summary by CodeRabbit

* **Chores**
  * Improved step-tracking with stable per-step IDs, added per-step metadata (iteration, task, input) and per-step caching; consistent stepId/runId propagation and explicit networkId context; aligned primitive identifier fields and payload shapes for network events.  
* **Bug Fixes**
  * Prevented duplicate step entries by updating steps in place to preserve accurate sequencing, statuses, and outputs.  
* **Tests**
  * Added network-stream tests validating chunk structure, step ordering, and task identifiers.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: client-sdks/ai-sdk/src/transformers.ts [hunk 1]
```diff
@@ -600,13 +658,20 @@ export function transformNetwork(
     case 'tool-execution-start': {
       const current = bufferedNetworks.get(payload.runId) || { name: '', steps: [], usage: null, output: null };
```
Comment (wardpeet) [inline client-sdks/ai-sdk/src/transformers.ts]:
```suggestion
      const current = bufferedNetworks.get(payload.runId);

      if (!current) return null;
```

File: client-sdks/ai-sdk/src/transformers.ts [hunk 2]
```diff
@@ -514,20 +528,50 @@ export function transformNetwork(
...
         bufferedNetworks.set(payload.runId, {
-          name: payload.payload.agentId,
+          name: payload.payload.networkId,
           steps: [],
           usage: null,
           output: null,
         });
       }
+
+      const current = bufferedNetworks.get(payload.runId)!;
```
Comment (LekoArts) [inline client-sdks/ai-sdk/src/transformers.ts:557]: In the other codepaths you don't force it with `!` and return null if undefined. On purpose here?

File: packages/core/src/loop/network/index.ts [hunk 3]
```diff
@@ -273,11 +273,13 @@ export async function createNetworkLoop({
       // to avoid treating 0 as falsy. Initial value is -1, so first iteration becomes 0.
       const iterationCount = (inputData.iteration ?? -1) + 1;
 
+      const stepId = generateId();
```
Comment (TheIsrael1) [inline packages/core/src/loop/network/index.ts:276]: will generating a stepId here as runId not make these chunks inconsistent with other chunks during the run.

Comment (wardpeet) [reply packages/core/src/loop/network/index.ts:276]: its per step so it's what i want

File: client-sdks/ai-sdk/src/transformers.ts (hunk 2 above)
Comment (wardpeet) [reply client-sdks/ai-sdk/src/transformers.ts:557]: yeah cause i check on has above

File: client-sdks/ai-sdk/src/__tests__/custom-data.test.ts [hunk 4]
```diff
@@ -396,4 +397,67 @@ describe('Custom Data Handling', () => {
       }
     });
   });
+
+  describe.only('network custom data', () => {
```
Comment (wardpeet) [inline client-sdks/ai-sdk/src/__tests__/custom-data.test.ts]:
```suggestion
  describe('network custom data', () => {
```
