### PR TITLE
fix: allow unsupported Zod types in tool outputSchema

### LINKED ISSUE #8040: [BUG] Cannot execute tools with tuple inside the outputSchema
### Describe the Bug

When I am using OpenRouter models and outputSchema of a tool contains a tuple, I get 

```
Error executing step prepare-tools-step: Error: openai/gpt-4.1-mini does not support zod type: ZodTuple
```

However, I believe that outputSchema isn't sent to the model so this should be not be happening. 

### Steps To Reproduce

1. Did `pnpm dlx create-mastra@latest`
2. Added `@openrouter/ai-sdk-provider`
3. Change the schema of the sample weatherTool (note the addition of the field `test` to:
```
export const weatherTool = createTool({
  id: "get-weather",
  description: "Get current weather for a location",
  inputSchema: z.object({
    location: z.string().describe("City name"),
  }),
  outputSchema: z.object({
    temperature: z.number(),
    feelsLike: z.number(),
    humidity: z.number(),
    windSpeed: z.number(),
    windGust: z.number(),
    conditions: z.string(),
    location: z.string(),
    test: z.tuple([z.string(), z.string()]),
  }),
  execute: async ({ context }) => {
    return await getWeather(context.location);
  },
});
```
4. Change the mode of weatherAgent to `model: createOpenRouter({
    apiKey: process.env.OPENROUTER_API_KEY,
  }).chat("openai/gpt-4.1-mini"),` 

5. Do `pnpm dev` and send something in the chat to an agent

### Expected Behavior

The model should be able to run with any outputSchema for tools.

### Environment Information

```json
{
    "@ai-sdk/openai": "^1.3.24",
    "@mastra/core": "^0.17.1",
    "@mastra/libsql": "^0.14.2",
    "@mastra/loggers": "^0.10.12",
    "@mastra/memory": "^0.15.2",
    "@openrouter/ai-sdk-provider": "^1.2.0",
}
```

Node v24.8

### Verification

- [x] I have searched the existing issues to make sure this is not a duplicate
- [x] I have included sufficient information for the team to reproduce and understand the issue

### PR DESCRIPTION
**Pull request by camachoh1**
## Summary

Fixes #8040 - Tools can now use any valid Zod type (including `ZodTuple`, `ZodIntersection`, etc.) in their `outputSchema` without triggering model compatibility errors.

## Problem

When creating a tool with `ZodTuple` in the `outputSchema`, the following error was thrown:
```
Error: openai/gpt-4.1-mini does not support zod type: ZodTuple
```

This happened because the tool builder was applying model-specific compatibility validation to `outputSchema`, even though **outputSchema is never sent to the LLM** - it's only used internally by Mastra for validating tool execution results.

## Solution

Modified `CoreToolBuilder.build()` in `packages/core/src/tools/tool-builder/builder.ts` to skip model compatibility layers for `outputSchema`:

**Before:**
```typescript
processedOutputSchema = applyCompatLayer({
  schema: this.getOutputSchema(),
  compatLayers: schemaCompatLayers,  // Applied model validation ❌
  mode: 'aiSdkSchema',
});
```

**After:**
```typescript
// Don't apply model compatibility layers to outputSchema since it's never sent to the LLM
processedOutputSchema = convertZodSchemaToAISDKSchema(this.getOutputSchema());
```

## Testing

Added comprehensive tests that verify:
1. ✅ `outputSchema` with `ZodTuple` no longer throws errors
2. ✅ `outputSchema` with `ZodIntersection` works correctly
3. ✅ `inputSchema` with `ZodTuple` still correctly throws errors (validation preserved)

All tests pass.

## Why This is Safe

- `outputSchema` is only used for internal validation of tool execution results
- The LLM only receives: `name`, `description`, and `parameters` (inputSchema)
- `inputSchema` still has full model compatibility validation
- This change aligns with the AI SDK's tool specification

Co-Authored-By: Richard LoRicco <rtlo9962@gmail.com>

## Summary by CodeRabbit

* **Bug Fixes**
  * Tool builds no longer apply compatibility-layer transformations to tool output schemas, so complex output types (e.g., tuples, intersections) are preserved and no longer trigger compatibility-related failures.

* **Tests**
  * Added a test ensuring complex output schemas are retained and exposed correctly when a tool is built.

* **Chores**
  * Added a changeset documenting the output schema validation fix.

---

> [!NOTE]
> Skips model compatibility on tool `outputSchema` so unsupported Zod types (e.g., `ZodTuple`) are allowed; adds a test and a changeset.
> 
> - **Core**
>   - Tool builder (`packages/core/src/tools/tool-builder/builder.ts`): do not apply schema compatibility layers to `outputSchema` (never sent to LLM); input schema handling unchanged.
> - **Tests**
>   - Add test in `builder.test.ts` verifying `outputSchema` can include `ZodTuple` without errors and remains defined after build.
> - **Docs/Release**
>   - Add changeset (`.changeset/fix-output-schema-zod-tuple.md`) documenting the validation fix.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit d12dff44b8c9a490b41def87bcac31814656d56c. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: packages/core/src/tools/tool-builder/builder.ts [hunk 1]
```diff
@@ -391,11 +391,10 @@ export class CoreToolBuilder extends MastraBase {
...
     if (this.getOutputSchema()) {
-      processedOutputSchema = applyCompatLayer({
-        schema: this.getOutputSchema(),
-        compatLayers: schemaCompatLayers,
-        mode: 'aiSdkSchema',
-      });
+      // Don't apply model compatibility layers to outputSchema since it's never sent to the LLM
+      // The outputSchema is only used internally for validation, so it can contain any valid Zod type
+      // including ZodTuple, ZodIntersection, etc. that some models don't support in their input schemas
+      processedOutputSchema = convertZodSchemaToAISDKSchema(this.getOutputSchema());
```
Comment (DanielSLew) [inline packages/core/src/tools/tool-builder/builder.ts]:
```suggestion
      // Don't add any compat layers to outputSchema since it's never sent to the LLM
      processedOutputSchema = applyCompatLayer({
        schema: this.getOutputSchema(),
        compatLayers: [],
        mode: 'aiSdkSchema'
      });
```

File: packages/core/src/tools/tool-builder/builder.test.ts [hunk 2]
```diff
@@ -987,3 +987,148 @@ describe('Tool Input Validation', () => {
     expect(result.message).toContain('"tags": []');
   });
 });
+
+describe('CoreToolBuilder Output Schema with Unsupported Types (Issue #8040)', () => {
+  // This test reproduces the bug reported in issue #8040
+  // Currently FAILS because outputSchema incorrectly applies compatibility layers
+  // Should PASS after fix
+  it('should allow ZodTuple in outputSchema even when model does not support it in inputSchema', () => {
```
Comment (DanielSLew) [inline packages/core/src/tools/tool-builder/builder.test.ts]: Clean up all the commends and test names and what not. Also this test is the only one that's needed, the others aren't.

**Review by DanielSLew — CHANGES_REQUESTED** [review]

File: packages/core/src/tools/tool-builder/builder.test.ts (hunk 2 above)
Comment (camachoh1) [reply packages/core/src/tools/tool-builder/builder.test.ts]: We made the changes as suggested. Thank you!

**Review by DanielSLew — APPROVED** [review]

**Review by kmk142789 — APPROVED** [review]

File: packages/core/src/tools/tool-builder/builder.test.ts [hunk 3]
```diff
@@ -949,3 +949,49 @@ describe('Tool Input Validation', () => {
...
+      description: 'Get weather information',
+      inputSchema: z.object({
+        location: z.string(),
+      }),
+      outputSchema: z.object({
+        temperature: z.number(),
+        conditions: z.string(),
+        test: z.tuple([z.string(), z.string()]),
+      }),
+      execute: async ({ context: _ }) => ({
```
Comment (DanielSLew) [inline packages/core/src/tools/tool-builder/builder.test.ts]: you can just remove variables if they're not being used
```suggestion
      execute: async () => ({
```

File: packages/core/src/tools/tool-builder/builder.test.ts [hunk 4]
```diff
@@ -949,3 +949,49 @@ describe('Tool Input Validation', () => {
...
+        temperature: 72,
+        conditions: 'sunny',
+        test: ['value1', 'value2'] as [string, string],
+      }),
+    });
+
+    const builder = new CoreToolBuilder({
+      originalTool: toolWithTupleOutput as any,
```
Comment (DanielSLew) [inline packages/core/src/tools/tool-builder/builder.test.ts]: Why did this have to be cast "as any"?

File: packages/core/src/tools/tool-builder/builder.test.ts [hunk 5]
```diff
@@ -949,3 +949,49 @@ describe('Tool Input Validation', () => {
...
+      options: {
+        name: 'weather-tool',
+        logger: console as any,
+        description: 'Get weather information',
+        runtimeContext: new RuntimeContext(),
```
Comment (DanielSLew) [inline packages/core/src/tools/tool-builder/builder.test.ts]:
```suggestion
        requestContext: new RequestContext(),
```
