### PR TITLE
fix(react): send dev playground header for localhost servers

### LINKED ISSUE #13488: Studio: x-mastra-dev-playground header not sent when using mastra studio with separate server
## Problem

When running `mastra studio` pointed at a separate local server (e.g. Hono on port 4000), the `x-mastra-dev-playground: true` header is never sent with API requests. This means the auth middleware's dev bypass (`MASTRA_DEV=true`) doesn't work in this scenario.

The root cause is in `client-sdks/react/src/mastra-client-context.tsx`:

```typescript
const createMastraClient = (baseUrl?: string, mastraClientHeaders: Record<string, string> = {}, apiPrefix?: string) => {
  return new MastraClient({
    baseUrl: baseUrl || '',
    headers: !baseUrl ? { ...mastraClientHeaders, 'x-mastra-dev-playground': 'true' } : mastraClientHeaders,
    apiPrefix,
  });
};
```

The header is only added when `baseUrl` is falsy (i.e. Studio and API on the same origin, the `mastra dev` case). When `baseUrl` is set — which is always the case with `mastra studio --server-port 4000` — the header is skipped.

## Expected behavior

When `mastra studio` points at a localhost server, the `x-mastra-dev-playground` header should be sent so the server-side auth bypass works with `MASTRA_DEV=true`.

## Steps to reproduce

1. Set up a Hono server with Mastra mounted at `/mastra` with auth configured
2. Run the Hono server with `MASTRA_DEV=true` on port 4000
3. Run `mastra studio --server-port 4000 --server-api-prefix /mastra`
4. Open Studio — all API calls fail with 401 because the dev playground header is missing

## Suggested fix

Update the condition in `createMastraClient` to also send the header when `baseUrl` points to localhost, e.g.:

```typescript
const isLocal = !baseUrl || baseUrl.includes('localhost') || baseUrl.includes('127.0.0.1');
headers: isLocal ? { ...mastraClientHeaders, 'x-mastra-dev-playground': 'true' } : mastraClientHeaders,
```

Related: #12371

### PR DESCRIPTION
**Pull request by graysonhicks**
## Description

Fixed the dev playground header not being sent when using `mastra studio --server-port`. The `x-mastra-dev-playground` header is now correctly included for localhost and 127.0.0.1 URLs, enabling the `MASTRA_DEV=true` auth bypass to work with separate local servers.

## Related Issue(s)

Fixes #13488

## Type of Change

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Code refactoring
- [ ] Performance improvement
- [ ] Test update

## Checklist

- [x] I have made corresponding changes to the documentation (if applicable)
- [x] I have added tests that prove my fix is effective or that my feature works

## Summary by CodeRabbit

* **Bug Fixes**
  * Dev-auth now correctly applies local development auth for requests to localhost, 127.0.0.1, IPv6 loopback, and hostnames ending with .local or .localhost; local behavior also applies when no base URL is provided.

* **Tests**
  * Added comprehensive tests validating local URL detection for empty/undefined, IPv4/IPv6 loopback, .local/.localhost, remote hosts, and edge-case hostnames.

* **Chores**
  * Added a changelog entry recording the patch.

### CODE REVIEW

File: client-sdks/react/src/mastra-client-context.tsx [hunk 1]
```diff
@@ -21,11 +21,20 @@ export const MastraClientProvider = ({ children, baseUrl, headers, apiPrefix }:
 
 export const useMastraClient = () => useContext(MastraClientContext);
 
+export const isLocalUrl = (url?: string): boolean => {
```
Comment (wardpeet) [inline client-sdks/react/src/mastra-client-context.tsx:32]: i wonder if this is better, actually resolving to localhost so mastra.local also works 🤷 
```
import { lookup } from 'node:dns/promises';
import { isLoopback } from 'node:net';

async function isLocalhostResolved(hostname) {
  // Quick check first
  if (isLocalhost(hostname)) return true;
  
  try {
    const { address } = await lookup(hostname);
    return net.isIP(address) && isLoopbackAddress(address);
  } catch {
    return false;
  }
}
```

Comment (graysonhicks) [reply client-sdks/react/src/mastra-client-context.tsx:32]: Hm, this is client context, don't think those node packages are available.

Comment (graysonhicks) [reply client-sdks/react/src/mastra-client-context.tsx:32]: I can still update to handle mastra.local I think

**Review by taofeeq-deru — APPROVED** [review]
