### PR TITLE
fix: implement Harness resource ID methods and improve /resource command

### LINKED ISSUE #13660: Mastra Code returns error when trying to use /resource command
This issue was created from Discord post 1477917247178674316:

[Open in Discord](https://discord.com/channels/1309558646228779139/1477917247178674316)

I am using mastra code version 0.4.0 installed via npm. When I try to call the /resource command, I get the following error:

Error: harness.getDefaultResourceId is not a function

It is not fatal, but it means I am unable to change the resource id or the scope in Mastra Code

### PR DESCRIPTION
**Pull request by NikAiyer**
## Description

Fix the `/resource` command which was broken due to unimplemented `getDefaultResourceId()` and `getKnownResourceIds()` methods on the Harness class. Also improved the `/resource` command UX so that switching resources resumes the most recent thread for that resource instead of always creating a new one.

**Changes:**

- **`@mastra/core`**: Added `getDefaultResourceId()` (returns the original resource ID from config) and `getKnownResourceIds()` (returns all unique resource IDs found across stored threads) to the Harness class.
- **`mastracode`**: Improved `/resource` command to resume the most recent thread when switching resources. If no threads exist for the target resource, a new thread is created. Added help text clarifying resource switching behavior.

Closes #13660 

## Type of Change

- [x] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Code refactoring
- [ ] Performance improvement
- [ ] Test update

## Checklist

- [ ] I have made corresponding changes to the documentation (if applicable)
- [x] I have added tests that prove my fix is effective or that my feature works

## Summary by CodeRabbit

* **New Features**
  - /resource now resumes the most recently used thread for a resource (creates a new thread only if none exist)
  - Clarified help text for resource-switching and reset behavior
  - Added public ways to get the default resource and list known resource IDs

* **Tests**
  - Added comprehensive tests covering /resource resume, reset, and no-thread scenarios and resource-ID utilities

### CODE REVIEW

**Review by DanielSLew — APPROVED** [review]

File: mastracode/src/tui/commands/resource.ts [hunk 1]
```diff
@@ -16,22 +16,48 @@ export async function handleResourceCommand(ctx: SlashCommandContext, args: stri
       ...knownIds.map((id: string) => `  ${id === current ? '* ' : '  '}${id}`),
       '',
       'Usage:',
-      '  /resource <id>    - Switch to a resource ID',
+      '  /resource <id>    - Switch to a resource ID (resumes latest thread)',
       '  /resource reset   - Reset to auto-detected ID',
```
Comment (DanielSLew) [inline mastracode/src/tui/commands/resource.ts]: don't we need something liek this too
```suggestion
      '  /resource <id>    - Switch to a resource ID (resumes latest thread)',
'  /resource reset   - Reset to auto-detected ID',
' /resource          - List and select from available resource ID's'
```

Comment (NikAiyer) [reply mastracode/src/tui/commands/resource.ts]: I can add that, but it automatically shows all the resource ids along with the usage already.
