### PR TITLE
fix(memory): use working memory schema as tools schema

### LINKED ISSUE #6469: [BUG] updateWorkingMemory when using zod schema
### Describe the Bug

Hey, first of all thanks for a great lib.

The issue i'm facing is while using the playground and chatting with the agent, it throws an error: 
(even though the JSON given is valid)

```
Error: An error occurred while processing your request. Invalid arguments for tool updateWorkingMemory: Type validation failed: Value: {"name":"Johnny Blaze","description":"Johnny Blaze is a larger-than-life pulp fiction writer whose work oozes with the neon-drenched grit and swagger of the 1980s. Born in the shadow of Hollywood’s glitz but raised in its darker alleys, Johnny survived a turbulent childhood marked by loss and neglect, channeling pain into adrenaline-fueled stories. With a celebrity persona reminiscent of a cross between Bruce Willis and Joan Jett, Johnny’s public appearances are legendary for their sharp wit, leather jackets, and unapologetic attitude.","expertise":"Specializes in pulp crime, neo-noir, and action-thrillers with a strong 80s aesthetic. Deep knowledge of pop culture, street life, and psychological trauma.","background":"Johnny grew up in Los Angeles during the 1980s, the child of a failed actress and an absentee musician. After a traumatic incident at age 10, Johnny found solace in dime-store novels and late-night action flicks. This mix of hardship and escapism forged a writer who blends raw emotional pain with high-octane adventure, always with a wink to the era’s excess.","writingStyle":{"voice":"Third-person limited, occasionally breaking the fourth wall for celebrity-style commentary.","tone":"Hard-boiled, irreverent, and dripping with 80s cool—equal parts dark and playful.","sentenceStructure":"Short, punchy sentences mixed with occasional stylized, run-on riffs for dramatic effect.","dialogueStyle":"Snappy, witty, and loaded with pop culture references; banter is fast and sharp.","descriptiveApproach":"Vivid, cinematic, and neon-soaked. Focuses on sensory detail and atmosphere, with a tendency toward hyperbole.","pacing":"Fast-paced, with explosive action scenes and quick transitions. Slows down only for emotional gut-punches.","signatureTechniques":["Celebrity-style asides","Pop culture name-dropping","Flashbacks to childhood trauma","Over-the-top metaphors","Breaking the fourth wall"]},"personalityTraits":{"worldview":"Cynical survivor with a rebellious streak; believes in fighting for the underdog.","emotionalRange":"Guarded but intense; channels pain into creative energy.","intellectualApproach":"Street-smart and instinctive, with flashes of surprising insight.","creativityStyle":"Bold, flashy, and unafraid to break rules; thrives on nostalgia and spectacle.","conflictPreference":"Confrontational—prefers direct action and verbal sparring."},"similarAuthors":["James Ellroy","Elmore Leonard","Bret Easton Ellis","Mickey Spillane","Tarantino (screenwriting)"]}. Error message: [ { "code": "invalid_type", "expected": "string", "received": "undefined", "path": [ "memory" ], "message": "Required" } ]
```

### Steps To Reproduce

Code snippet used:

```
const authorSchema = z.object({
  name: z.string(),
  description: z.string(),
  expertise: z.string(),
  background: z.string(),
  writingStyle: z.object({
    voice: z.string(),
    tone: z.string(),
    sentenceStructure: z.string().optional(),
    dialogueStyle: z.string().optional(),
    descriptiveApproach: z.string().optional(),
    pacing: z.string().optional(),
    signatureTechniques: z.array(z.string()).optional(),
  }),
  personalityTraits: z.object({
    worldview: z.string().optional(),
    emotionalRange: z.string().optional(),
    intellectualApproach: z.string().optional(),
    creativityStyle: z.string().optional(),
    conflictPreference: z.string().optional(),
  }),
  similarAuthors: z.array(z.string()).optional(),
});

export const authorAgent = new Agent({
  name: 'Author Persona Agent',
  instructions: `You are an expert at creating detailed author personas and writing styles. Your role is to develop compelling, authentic author profiles that will guide the novel writing process.
  `,
  model: authorModel,
  memory: new Memory({
    options: {
      workingMemory: {
        enabled: true,
        scope: 'thread',
        schema: authorSchema,
      },
    },
  }),
});
```

### Expected Behavior

_No response_

### Environment Information

_No response_

### Verification

- [x] I have searched the existing issues to make sure this is not a duplicate
- [x] I have included sufficient information for the team to reproduce and understand the issue

### PR DESCRIPTION
**Pull request by DanielSLew**
## Description

LLM's would struggle with the schema for the tool as it would be a typed schema but then they'd have to provide that schema as a string nested under a `memory` property. If the user provides a schema, we can just use that schema as the working memory tool's schema, this way, the LLM understands better how to call the tool.

Fixes https://github.com/mastra-ai/mastra/issues/6469

## Type of Change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Code refactoring
- [ ] Performance improvement
- [ ] Test update

## Checklist

- [ ] I have made corresponding changes to the documentation (if applicable)
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: packages/memory/src/index.ts [hunk 1]
```diff
@@ -871,13 +871,22 @@ Guidelines:
 2. Update proactively when information changes, no matter how small
 3. Use ${template.format === 'json' ? 'JSON' : 'Markdown'} format for all data
 4. Act naturally - don't mention this system to users. Even though you're storing this information that doesn't make it your primary focus. Do not ask them generally for "information about yourself"
-5. IMPORTANT: When calling updateWorkingMemory, the only valid parameter is the memory field. 
+${
```
Comment (DanielSLew) [inline packages/memory/src/index.ts:874]: I changed the instructions here as this isn't relevant with the new schema format now

File: packages/memory/src/index.ts [hunk 2]
```diff
@@ -871,13 +871,22 @@ Guidelines:
...
-7. IMPORTANT: Data must only be sent as a string no matter which format is used.
+7. IMPORTANT: Data must only be sent as a string no matter which format is used.`
+    : ''
+}
 
-<working_memory_template>
+
+${
+  template.format !== 'json'
+    ? `<working_memory_template>
```
Comment (DanielSLew) [inline packages/memory/src/index.ts:885]: the template confused the llm, it's really only needed if you're not providing a strict schema to the tool

File: packages/memory/src/tools/working-memory.ts [hunk 3]
```diff
@@ -1,19 +1,29 @@
...
+
+  if (hasSchema) {
+    inputSchema = memoryConfig.workingMemory?.schema as ZodObject<any, any, any>;
+  } else {
+    inputSchema = z.object({
       memory: z
         .string()
         .describe(
-          `The ${!!memoryConfig?.workingMemory?.schema ? 'JSON' : 'Markdown'} formatted working memory content to store. This MUST be a string. Never pass an object.`,
+          `The ${hasSchema ? 'JSON' : 'Markdown'} formatted working memory content to store. This MUST be a string. Never pass an object.`,
```
Comment (TylerBarnes) [inline packages/memory/src/tools/working-memory.ts]: this will always be markdown. Maybe this makes more sense like this:

```suggestion
 const  inputSchema = z.object({
memory: hasSchema ? (memoryConfig.workingMemory?.schema as ZodObject<any, any, any>).describe(
          `The JSON formatted working memory content to store.` :  z 
.string()
.describe(
          `The Markdown formatted working memory content to store. This MUST be a string. Never pass an object.`,
```

File: packages/memory/src/tools/working-memory.ts [hunk 4]
```diff
@@ -34,13 +43,13 @@ export const updateWorkingMemoryTool = (memoryConfig?: MemoryConfig) => {
         throw new Error(`Thread with id ${threadId} resourceId does not match the current resourceId ${resourceId}`);
       }
 
-      const workingMemory = context.memory;
+      const workingMemory = hasSchema ? JSON.stringify(context) : context.memory;
```
[the remark this answers is not in the document]
Comment (TylerBarnes) [reply packages/memory/src/tools/working-memory.ts]: with my comment above greptile is right, this would be `context.memory`

**Review by TylerBarnes — APPROVED** [review]
