### PR TITLE
fix(core, pg): ensure correct tool call and result message order when using Memory semanticRecall

### LINKED ISSUE #2012: Playground doesn't work too well with persisted messages
When we're persisting messages in the DB and there's a tool call involved, it seems like we are not sending the right array of messages to the LLM.

With OpenAI provider:
Image

With Google Generative AI Provider:
Image

It's probably because on subsequent messages, the previous tool calls are not sent to the LLM perhaps?

### PR DESCRIPTION
**Pull request by TylerBarnes**
Fixes https://github.com/mastra-ai/mastra/issues/2012

There were 2 problems: 
1. sometimes we were setting the exact same date on multiple messages, meaning sorting them later by date might get the order wrong - now they're always atleast 1ms apart to preserve sort order by date
2. we were sorting by id and created date for PG vector results, which sometimes messed up tool call order

### CODE REVIEW

File: packages/core/src/agent/index.ts [hunk 1]
```diff
@@ -326,56 +326,58 @@ export class Agent<
...
-                }>;
-
-                toolCallIds = assistantToolCalls?.map(toolCall => toolCall.toolCallId);
-
-                toolCallArgs = assistantToolCalls?.map(toolCall => toolCall.toolArgs);
-                toolNames = assistantToolCalls?.map(toolCall => toolCall.toolName);
-                type = assistantContent?.[0]?.type as 'text' | 'tool-call' | 'tool-result';
-              }
+            messages: responseMessagesWithoutIncompleteToolCalls.map(
+              (message: CoreMessage | CoreAssistantMessage, index) => {
```
Comment (TylerBarnes) [inline packages/core/src/agent/index.ts:330]: huge diff here cause I added `index` to this line which changed indenting for everything

File: packages/core/src/agent/index.ts [hunk 2]
```diff
@@ -326,56 +326,58 @@ export class Agent<
...
+                  toolNames = assistantToolCalls?.map(toolCall => toolCall.toolName);
+                  type = assistantContent?.[0]?.type as 'text' | 'tool-call' | 'tool-result';
+                }
+
+                return {
+                  id: messageId,
+                  threadId: threadId,
+                  role: message.role as any,
+                  content: message.content as any,
+                  createdAt: new Date(Date.now() + index), // use Date.now() + index to make sure every message is atleast one millisecond apart
```
Comment (TylerBarnes) [inline packages/core/src/agent/index.ts:373]: This is fix 1

**Review by abhiaiyer91 — APPROVED** [review]
