### PR TITLE
Bug/aws bedrock agent memory

### LINKED ISSUE #5465: [BUG] Using the default options for agent memory and a aws bedrock provider fails after n messages in thread
### Describe the Bug

I am using an agent with a bedrock provided model and memory configured with LibSQL. I use the client-js sdk to call the agent to stream passing messages, runtimeContext and a memory config with threadId and resourceId. 
This is working up to a point where, I think, the messages from memory reach the `lastMessages` limit, pruning takes place and the final messages list passed to the agent doesn't have a user message as the first one. Bedrock seems to fail on that with an error: 
```
{error: '"An error occurred while processing your request. undefined: A conversation must start with a user message. Try again with a conversation that starts with a user message."'}
```

### Steps To Reproduce

1. Define a mastra agent with a bedrock provided model like so: 
```
const bedrock = createAmazonBedrock({
      region,
      credentialProvider: fromNodeProviderChain(),
    })

const myAgent = new Agent({
  name: "My Agent",
  model: bedrock(modelId),
  ...,
  memory: new Memory({
    options: {
      generateTitle: true
    }
  })
})
```

2. Call the agent from a web page using the client-js sdk like so: 
```
const stream = await agent.stream({
          messages: [
            {
              role: "user",
              content: inputData.prompt,
            },
          ],
          runtimeContext,
          memory: {
            thread: threadId,
            resource: RESOURCE_ID,            
          },
        })
```

3. If the messages in the thread exceed the default lastMessages limit the process of concatenating the memory's messages with the user ones seems that doesn't fulfill the bedrock's provider expectation that the first message is a user one. 

### Expected Behavior

We shouldn't get an error but instead, I think, make sure that when concatenating the memory's messages make sure to keep the first user message in place. 

### Environment Information

_No response_

### Verification

- [x] I have searched the existing issues to make sure this is not a duplicate
- [x] I have included sufficient information for the team to reproduce and understand the issue

### PR DESCRIPTION
**Pull request by nickperry12**
## Description
- Fixed an issue where AWS Bedrock expects a user message at the start of a conversation
- Added logic that checks for an empty list, or check if the start of the list begins with a message that isn't a user or system message, and appends a user message if so
- Commented out the logic, function and import for iterating through the message list and removing tool call messages. This fix should also address this, making it unnecessary. Can fully remove all that logic if everything looks good.

## Related Issue(s)

Fixes #5465 

## Type of Change

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Code refactoring
- [ ] Performance improvement
- [ ] Test update

## Checklist

- [ ] I have made corresponding changes to the documentation (if applicable)
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: packages/core/src/agent/message-list/index.ts [hunk 1]
```diff
@@ -114,11 +114,24 @@ export class MessageList {
...
-        coreMessages.shift();
-      }
+      // while (coreMessages[0] && isToolCallMessage(coreMessages[0])) {
+      //   coreMessages.shift();
+      // }
 
       const messages = [...this.systemMessages, ...Object.values(this.taggedSystemMessages).flat(), ...coreMessages];
+
+      const needsDefaultUserMessage =
+        messages.length === 0 || (messages[0] && messages[0].role !== 'user' && messages[0].role !== 'system');
```
[the remark this answers is not in the document]
Comment (nickperry12) [reply packages/core/src/agent/message-list/index.ts]: @greptileai good catch, made the change

File: packages/core/src/agent/message-list/index.ts [hunk 2]
```diff
@@ -114,11 +114,23 @@ export class MessageList {
...
+      // }
 
       const messages = [...this.systemMessages, ...Object.values(this.taggedSystemMessages).flat(), ...coreMessages];
+
+      const needsDefaultUserMessage = !messages.length || messages[0]?.role === 'assistant';
+
+      if (needsDefaultUserMessage) {
+        const defaultMessage: CoreMessage = {
+          role: 'user',
+          content: 'hello',
```
Comment (DanielSLew) [inline packages/core/src/agent/message-list/index.ts]:
```suggestion
          content: '.',
```

File: packages/core/src/agent/message-list/index.ts [hunk 3]
```diff
@@ -114,11 +114,23 @@ export class MessageList {
       const coreMessages = this.all.core();
 
       // Some LLM providers will throw an error if the first message is a tool call.
-      while (coreMessages[0] && isToolCallMessage(coreMessages[0])) {
-        coreMessages.shift();
-      }
+      // while (coreMessages[0] && isToolCallMessage(coreMessages[0])) {
+      //   coreMessages.shift();
+      // }
```
Comment (DanielSLew) [inline packages/core/src/agent/message-list/index.ts]:
```suggestion
```

File: packages/core/src/agent/message-list/index.ts [hunk 4]
```diff
@@ -29,15 +29,15 @@ export type MastraMessageV2 = {
...
-}
+// function isToolCallMessage(message: CoreMessage): boolean {
+//   if (message.role === 'tool') {
+//     return true;
+//   }
+//   if (message.role === 'assistant' && Array.isArray(message.content)) {
+//     return message.content.some((part): part is ToolCallPart => part.type === 'tool-call');
+//   }
+//   return false;
+// }
```
Comment (DanielSLew) [inline packages/core/src/agent/message-list/index.ts]:
```suggestion
```

File: packages/core/src/agent/message-list/index.ts [hunk 5]
```diff
@@ -1,6 +1,6 @@
 import { randomUUID } from 'crypto';
 import { convertToCoreMessages } from 'ai';
-import type { CoreMessage, CoreSystemMessage, IDGenerator, Message, ToolCallPart, ToolInvocation, UIMessage } from 'ai';
+import type { CoreMessage, CoreSystemMessage, IDGenerator, Message, ToolInvocation, UIMessage } from 'ai'; // removed ToolCallPart for linter
```
Comment (DanielSLew) [inline packages/core/src/agent/message-list/index.ts]:
```suggestion
import type { CoreMessage, CoreSystemMessage, IDGenerator, Message, ToolInvocation, UIMessage } from 'ai';
```

**Review by DanielSLew — CHANGES_REQUESTED** [review]

File: packages/core/src/agent/message-list/index.ts [hunk 6]
```diff
@@ -29,15 +29,20 @@ export type MastraMessageV2 = {
...
+
+function isToolCallMessage(message: CoreMessage): boolean {
+  if (message.role === 'tool') {
+    return true;
+  }
+  if (message.role === 'assistant' && Array.isArray(message.content)) {
+    return message.content.some((part): part is ToolCallPart => part.type === 'tool-call');
+  }
+  return false;
+}
```
Comment (DanielSLew) [inline packages/core/src/agent/message-list/index.ts]: Isn't this not being used anymore?

Comment (nickperry12) [reply packages/core/src/agent/message-list/index.ts]: It's not! Just pushed a commit that removed it, must've missed it when merging changes

**Review by DanielSLew — APPROVED** [review]
