### PR TITLE
fix(server): Correct `agentIds` for scorers endpoint

### LINKED ISSUE #6652: [BUG] Playground: broken link from scorer to agent
### Describe the Bug

Image

When on `/scorers/<scorerId>`, the link back to the agent uses the agent name instead of the agent id to link back to the agent page -> 404 if the two are not identical.

Link from the scorer page:

Image

Link from the agent directory:

Image

### Steps To Reproduce

1. Create an agent with an id different from its name
2. Add a scorer
3. Run the playground
4. Go to the agent page
5. Click on the scorer to see the scorer page
6. Try to navigate back to the agent using the link next to "Entities"

### Expected Behavior

_No response_

### Environment Information

├── @ai-sdk/openai@1.3.23
├── @mastra/core@0.13.1
├── @mastra/evals@0.12.0
├── @mastra/libsql@0.13.1
├── @mastra/loggers@0.10.6
├── @mastra/memory@0.12.1
├── mastra@0.10.20

### Verification

- [x] I have searched the existing issues to make sure this is not a duplicate
- [x] I have included sufficient information for the team to reproduce and understand the issue

### PR DESCRIPTION
**Pull request by LekoArts**
## Description

Currently the `/api/scores/scorers` and `/api/scores/scorers/${scorerId}` return an incorrect object where the `agentIds` contains the name, not the id. This PR fixes this small typo.

While debugging this issue I found two instances of stray `console.log()` calls and typos in the test for the scores handler which I fixed.

I'd like to add tests for this fix but I'm not sure how to properly mock the `runtimeContext`

## Related Issue(s)

Fixes https://github.com/mastra-ai/mastra/issues/6652

## Type of Change

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Code refactoring
- [ ] Performance improvement
- [ ] Test update

## Checklist

- [ ] I have made corresponding changes to the documentation (if applicable)
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: packages/server/src/server/handlers/scores.ts [hunk 1]
```diff
@@ -29,7 +29,7 @@ async function getScorersFromSystem({
           scorersMap.set(scorerId, {
             workflowIds: [],
             ...scorer,
-            agentIds: [agent.name],
+            agentIds: [agentId],
```
Comment (LekoArts) [inline packages/server/src/server/handlers/scores.ts:32]: This is the actual fix

**Review by TheIsrael1 — APPROVED** [review]
