### PR TITLE
fix(trace-span-usage): enhance component to handle nested object valu…

### LINKED ISSUE #11140: Mastra Studio (mastra beta.9) crash in the observability section
This issue was created from Discord post 1449142509619118283:

[Open in Discord](https://discord.com/channels/1309558646228779139/1449142509619118283)

In the observability section, when i try to check the info of an agent call it crash.

### PR DESCRIPTION
**Pull request by roaminro**
## Description

…es in token usage data

Updated the trace-span-usage component to properly manage object values in token usage data, including nested properties for input and output details. The component now type-checks these values and renders them as nested key-value pairs, improving the display of token usage information.
## Related Issue(s)

fixes #11140

## Type of Change

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Code refactoring
- [ ] Performance improvement
- [ ] Test update

## Checklist

- [ ] I have made corresponding changes to the documentation (if applicable)
- [ ] I have added tests that prove my fix is effective or that my feature works

## Summary by CodeRabbit

* **New Features**
  * Shows a detailed token-usage breakdown: supports nested input/output detail objects and renders per-item key/value lines for clearer insight.

* **Bug Fixes**
  * Fixed token-usage rendering when usage values are objects instead of numbers, preserving provider-specific token totals and legacy numeric displays.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: packages/playground-ui/src/domains/observability/components/trace-span-usage.tsx [hunk 1]
```diff
@@ -2,13 +2,31 @@ import { cn } from '@/lib/utils';
...
+  image?: number;
+};
+
+type OutputTokenDetails = {
+  text?: number;
+  reasoning?: number;
+  audio?: number;
+  image?: number;
+};
+
```
Comment (epinzur) [inline packages/playground-ui/src/domains/observability/components/trace-span-usage.tsx]: instead of creating new types, can you just use the existing types from `@mastra/core/observability` ?

Comment (mfrachet) [reply packages/playground-ui/src/domains/observability/components/trace-span-usage.tsx]: ☝🏻 once this is done, let's merge that

**Review by TheIsrael1 — APPROVED** [review]
