### PR TITLE
[MASTRA-2830] fix if-else execution

### LINKED ISSUE #3348: [BUG] if-else branches skip steps
### Describe the Bug

I have this workflow with multiple if else branches
```
workflow
    .step(parseContractStep)
    .if(async ({ context }) => {
      const parseResult = context.getStepResult<{ success: boolean }>("parse-contract");
      return parseResult?.success ?? false;
    })
    .then(scrapeEtherscanLabelsStep)
    .if(async ({ context }) => {
      const scrapeResult = context.getStepResult<{ nameTag: string; deployerNameTag: string }>(
        "scrape-etherscan-labels",
      );
      return scrapeResult?.nameTag !== null || scrapeResult?.deployerNameTag !== null;
    })
    .then(concludeEtherscanLabelsStep)
    .then(
      new Step({
        id: "conclusion-success",
        outputSchema: labelFinalOutput,
        execute: async ({ context }) => ({
          label_found:
            context.getStepResult<{ label_found: boolean }>("conclude-etherscan-labels")?.label_found ?? false,
          label: context.getStepResult<{ label: string }>("conclude-etherscan-labels")?.label ?? null,
        }),
      }),
    )
    .else()
    .then(getSummaryStep)
    .then(searchLinksStep)
    .then(concludeInternalStep)
    .then(
      new Step({
        id: "conclusion-success",
        outputSchema: labelFinalOutput,
        execute: async ({ context }) => ({
          label_found: context.getStepResult<{ label_found: boolean }>("conclude-internal")?.label_found ?? false,
          label: context.getStepResult<{ label: string }>("conclude-internal")?.label ?? null,
        }),
      }),
    )
    .else()
    .then(
      new Step({
        id: "conclusion-failed",
        outputSchema: labelFinalOutput,
        execute: async () => ({
          label_found: false,
          label: null,
        }),
      }),
    )
    .commit();
```

However this is what it's output looks like: 
```
{
  "parse-contract": {
    status: "success",
    output: {
      success: true,
    },
  },
  "__parse-contract_else": {
    status: "skipped",
  },
  "__parse-contract_if": {
    status: "success",
    output: {
      executed: true,
    },
  },
  "____parse-contract_if_else": {
    status: "skipped",
  },
  "____parse-contract_if_if": {
    status: "success",
    output: {
      executed: true,
    },
  },
  "conclude-etherscan-labels": {
    status: "success",
    output: {
      label_found: false,
      label: null,
    },
  },
  "conclusion-success": {
    status: "success",
    output: {
      label_found: false,
      label: null,
    },
  },
  "scrape-etherscan-labels": {
    status: "success",
    output: {
      nameTag: "Circle: USDC Token",
      deployerNameTag: "Circle: Deployer",
    },
  },
}
```

It should be calling scrape-etherscan-labels after the __parse-contract_if step, but it is for some reason skipping it and going directly to the next if instead

### Steps To Reproduce

"@mastra/core": "^0.6.4",

@YujohnNattrass  has a minimal reproduction that I don't have the code to

### Expected Behavior

Should follow the if else nested branches correctly

### Environment Information

"@mastra/core": "^0.6.4",

### Component

Workflows

### Code Snippet

```typescript
above
```

### Error Logs

```shell
no error logs, it just takes the wrong pat
```

### Additional Context

_No response_

### Verification

- [x] I have searched the existing issues to make sure this is not a duplicate
- [x] I have included sufficient information for the team to reproduce and understand the issue

### PR DESCRIPTION
**Pull request by adeniyii**
## Description

- Enter into limbo state on if-else branch when condition fails. This makes sure inner steps/conditions are not getting executed on a branch with a failed parent condition.
- Enable correct execution order when stacking or nesting if-else conditions

## Related Issue(s)

Closes #3348 

## Type of Change

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [x] Code refactoring
- [ ] Performance improvement
- [ ] Test update

## Checklist

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation (if applicable)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have generated a changeset for this PR

### CODE REVIEW

**Comment by wardpeet** [comment]
I don't see a test that says this is fixed, can you add one?

**Comment by adeniyii** [comment]
> I don't see a test that says this is fixed, can you add one?

@wardpeet I've added a couple of tests in 👍

File: packages/core/src/workflows/workflow.ts [hunk 1]
```diff
@@ -1190,8 +1244,14 @@ export class Workflow<
     return this.#serializedStepSubscriberGraph;
   }
 
-  get steps() {
-    return this.#steps;
+  get steps(): Record<string, StepAction<string, any, any, any>> {
+    return Object.entries(this.#steps).reduce(
```
Comment (wardpeet) [inline packages/core/src/workflows/workflow.ts:1252]: can you explain what you're doing here? You're cloning the object?

File: packages/core/src/workflows/workflow.ts [hunk 2]
```diff
@@ -978,6 +1018,20 @@ export class Workflow<
     return parentStepKey;
   }
 
+  #getLastStep({ if_else_check }: { if_else_check: boolean }) {
```
Comment (wardpeet) [inline packages/core/src/workflows/workflow.ts:1023]: Ask claude to clean this up, the if case is hard to read :)

File: packages/core/src/workflows/workflow.ts [hunk 3]
```diff
@@ -965,11 +995,21 @@ export class Workflow<
...
+  ) {
     let parentStepKey = undefined;
     for (let i = this.#afterStepStack.length - 1; i >= 0; i--) {
       const stepKey = this.#afterStepStack[i];
-      if (stepKey && this.#stepSubscriberGraph[stepKey] && (loop_check ? !stepKey.includes('loop_check') : true)) {
+      if (
+        stepKey &&
+        this.#stepSubscriberGraph[stepKey] &&
+        (loop_check ? !stepKey.includes('loop_check') : true) &&
+        (if_else_check ? !isConditionalKey(stepKey) : true)
```
Comment (wardpeet) [inline packages/core/src/workflows/workflow.ts]: try to move things out of the if, makes it hard to read or ask claude :)

**Review by wardpeet — COMMENTED** [review]
added some small clenaups

File: packages/core/src/workflows/workflow.ts (hunk 1 above)
Comment (adeniyii) [reply packages/core/src/workflows/workflow.ts:1252]: I changed the interface of the private `this.#steps` property, however there are places outside of core depending on the former structure through the getter. 

This change here is building out the expected structure.

You'll notice I'm picking the `step` member from the main step:

```ts
(acc, [key, step]) => {
  acc[key] = step.step;
  return acc;
},
```

**Review by rase- — APPROVED** [review]
