### PR TITLE
fix(@mastra/ai-sdk): ensure proper forwarding of requestContext in ch…

### LINKED ISSUE #11192: requestContext not working on chatRoute and networkRoute
This issue was created from Discord post 1450281655880126494:

[Open in Discord](https://discord.com/channels/1309558646228779139/1450281655880126494)

I'm using the beta versions of Mastra, and I'm experiencing an issue with chatRoute and networkRoute. If I use Mastra Studio directly, the requestContext is set correctly and I can use it, but when using the routes for the AI ​​SDK, it isn't set and is always empty in the agent, tools, workflows, etc.

```typescript
import { chatRoute } from '@mastra/ai-sdk';
import { quoteAgentMiddleware } from '../middleware';
import { gmailRoutes } from '../routes/integrations/gmail.routes';
import { platformRoutes } from '../routes/platform.routes';
import { corsConfig } from './cors';

export const serverConfig = {
    cors: corsConfig,
    middleware: [
        {
            handler: quoteAgentMiddleware,
            path: '/agent/quote-agent/*',
        },
    ],
    apiRoutes: [
        chatRoute({
            path: '/platform/chat',
            agent: 'platformAgent',
        }),
        chatRoute({
            path: '/agent/quote-agent/chat',
            agent: 'quoteAgent',
        }),
    ],
};
```

Before the update (with runtimeContext) this code worked:

```typescript
export const quoteAgentMiddleware: MiddlewareHandler = async (c, next) => {
    const requestContext = c.get('requestContext') as RequestContext;

    // Extract data from body
    let body: { agentId?: string; organizationId?: string };
    try {
        const clonedRequest = c.req.raw.clone();
        body = await clonedRequest.json();
    } catch {
        return c.json({ error: 'Invalid request body. Expected JSON.' }, 400);
    }

    // Validate required fields
    if (!body.agentId) {
        return c.json({ error: 'agentId is required in request body' }, 400);
    }

    if (!body.organizationId) {
        return c.json({ error: 'organizationId is required in request body' }, 400);
    }

    // Store in requestContext
    requestContext.set('agentId', body.agentId);
    requestContext.set('organizationId', body.organizationId);

    await next();
};
```

### PR DESCRIPTION
**Pull request by roaminro**
…atRoute and networkRoute

This commit addresses an issue where the requestContext set by middleware was not being correctly forwarded in the chatRoute and networkRoute of the AI SDK. The fix prioritizes the requestContext from middleware over default options and request body, ensuring that the correct context is passed to agents and tools. Additionally, any requestContext from the request parameters is removed to avoid ambiguity.

Resolves #11192

## Type of Change

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Code refactoring
- [ ] Performance improvement
- [ ] Test update

## Checklist

- [ ] I have made corresponding changes to the documentation (if applicable)
- [ ] I have added tests that prove my fix is effective or that my feature works

## Summary by CodeRabbit

* **Bug Fixes**
  * Fixed request-context forwarding so middleware context takes precedence over route options, which take precedence over request body, ensuring the correct context is used during agent and tool execution.
  * Removed ambiguous context propagation from request parameters and added warnings when multiple context sources conflict to surface resolution behavior.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: client-sdks/ai-sdk/src/network-route.ts [hunk 1]
```diff
@@ -181,26 +181,30 @@ export function networkRoute<OUTPUT extends OutputSchema = undefined>({
...
 
-      if (routeRequestContext && params.requestContext) {
+      if (contextRequestContext && params.requestContext) {
         mastra
           .getLogger()
           ?.warn(
-            `"requestContext" from the request body will be ignored because "requestContext" is already set in the route options.`,
+            `"requestContext" from the request body will be ignored because "requestContext" is already set by middleware or route options.`,
           );
       }
```
Comment (graysonhicks) [inline client-sdks/ai-sdk/src/network-route.ts:196]: Do we need to warn where `defaultOptions?.requestContext` is set and `params.requestContext` is in the body (but no middleware context)?  The body value is also ignored in that case.

File: client-sdks/ai-sdk/src/chat-route.ts [hunk 2]
```diff
@@ -304,25 +304,30 @@ export function chatRoute<OUTPUT extends OutputSchema = undefined>({
...
+            `"requestContext" from the request body will be ignored because "requestContext" is already set by middleware or route options.`,
           );
       }
 
       if (!agentToUse) {
         throw new Error('Agent ID is required');
       }
 
+      // Remove requestContext from params to avoid confusion, then explicitly pass the effective one
+      const { requestContext: _unusedRequestContext, ...paramsWithoutContext } = params;
```
Comment (wardpeet) [inline client-sdks/ai-sdk/src/chat-route.ts]:
```suggestion
```

File: client-sdks/ai-sdk/src/chat-route.ts [hunk 3]
```diff
@@ -304,25 +304,30 @@ export function chatRoute<OUTPUT extends OutputSchema = undefined>({
...
+
       const uiMessageStream = await handleChatStream<UIMessage, OUTPUT>({
         mastra,
         agentId: agentToUse,
         params: {
-          ...params,
-          requestContext: contextRequestContext || params.requestContext,
+          ...paramsWithoutContext,
```
Comment (wardpeet) [inline client-sdks/ai-sdk/src/chat-route.ts]:
```suggestion
          ...params,
```

File: client-sdks/ai-sdk/src/network-route.ts [hunk 4]
```diff
@@ -181,26 +181,30 @@ export function networkRoute<OUTPUT extends OutputSchema = undefined>({
...
+      // Remove requestContext from params to avoid confusion, then explicitly pass the effective one
+      const { requestContext: _unusedRequestContext, ...paramsWithoutContext } = params;
+
       const uiMessageStream = await handleNetworkStream<UIMessage, OUTPUT>({
         mastra,
         agentId: agentToUse,
         params: {
-          ...params,
-          requestContext: routeRequestContext || params.requestContext,
+          ...paramsWithoutContext,
```
Comment (wardpeet) [inline client-sdks/ai-sdk/src/network-route.ts]:
```suggestion
          ...params,
```

File: client-sdks/ai-sdk/src/network-route.ts [hunk 5]
```diff
@@ -181,26 +181,30 @@ export function networkRoute<OUTPUT extends OutputSchema = undefined>({
...
+            `"requestContext" from the request body will be ignored because "requestContext" is already set by middleware or route options.`,
           );
       }
 
       if (!agentToUse) {
         throw new Error('Agent ID is required');
       }
 
+      // Remove requestContext from params to avoid confusion, then explicitly pass the effective one
+      const { requestContext: _unusedRequestContext, ...paramsWithoutContext } = params;
```
Comment (wardpeet) [inline client-sdks/ai-sdk/src/network-route.ts]:
```suggestion
```

**Review by wardpeet — COMMENTED** [review]
no need to remove requestContext, merging already takes care of it

**Review by TheIsrael1 — APPROVED** [review]
