### PR TITLE
Fix/11253  detect bun for bun globals

### LINKED ISSUE #11253: [BUG] Bun S3 API's not working inside Mastra Workflows
### Describe the Bug

- i run my app on bun runtime
- when using bun's native s3 client inside a workflow step throwing an error saying bun not found.
- may be a runtime issue as mastra workflows run under the node.

### Steps To Reproduce

1. create a bun project
2. install mastra
3. create a workflow 
4. in the step of workflow try to do any operations with bun's native s3 client.
5. can see error in the console log

### Link to Minimal Reproducible Example

https://github.com/mastra-ai/mastra

### Expected Behavior

- it should run bun natives api's as it allows bun runtime

### Environment Information

```block
- bun
```

### Verification

- [x] I have searched the existing issues to make sure this is not a duplicate
- [x] I have included sufficient information for the team to reproduce and understand the issue

### PR DESCRIPTION
**Pull request by graysonhicks**
## Description

Fixes Bun S3 APIs not working inside Mastra Workflows by detecting the runtime environment and configuring esbuild accordingly.

**Problem:** The Mastra bundler hardcoded `platform: 'node'` in esbuild configuration, which causes Bun-specific globals (like `Bun.s3`) to be unavailable when workflow steps execute. When running under Bun, this resulted in "bun not found" errors.

**Solution:** 
- Added `detectRuntime()` utility that checks for `globalThis.Bun` to identify the runtime
- Added `getEsbuildPlatform()` that returns `'neutral'` for Bun (preserving globals) or `'node'` for Node.js
- Introduced `BundlerPlatform` type (`'node' | 'browser' | 'neutral'`) for type safety
- Updated all hardcoded platform locations in `DevBundler.ts`, `bundler/index.ts`, and `watcher.ts`
- Platform is evaluated once at module load time for efficiency

**Files changed:**
- `packages/deployer/src/build/utils.ts` — Added runtime detection utilities
- `packages/deployer/src/build/index.ts` — Exported new utilities and types
- `packages/deployer/src/build/watcher.ts` — Updated to use `BundlerPlatform` type
- `packages/deployer/src/build/bundler.ts` — Updated platform parameter type
- `packages/deployer/src/build/analyze.ts` — Updated platform option type
- `packages/deployer/src/bundler/index.ts` — Uses `getEsbuildPlatform()` 
- `packages/cli/src/commands/dev/DevBundler.ts` — Uses `getEsbuildPlatform()`

## Related Issue(s)

Fixes #11253

## Type of Change

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Code refactoring
- [ ] Performance improvement
- [x] Test update

## Checklist

- [] I have made corresponding changes to the documentation (if applicable)
- [x] I have added tests that prove my fix is effective or that my feature works

## Summary by CodeRabbit

* **New Features**
  - Automatic runtime detection to choose the bundler platform.
  - Builds preserve Bun-specific globals/APIs to avoid incorrect transformations.

* **Refactor**
  - Build and bundler tooling made platform-aware so the chosen platform is consistently propagated.

* **Tests**
  - Added tests for runtime detection and platform propagation in the build/watch flows.

* **Chores**
  - Release metadata updated to document Bun runtime handling.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: packages/deployer/src/bundler/index.ts [hunk 1]
```diff
@@ -14,13 +14,16 @@ import { createBundler as createBundlerUtil, getInputOptions } from '../build/bu
...
-import { getPackageName, slash } from '../build/utils';
+import { getPackageName, slash, getEsbuildPlatform } from '../build/utils';
 import { DepsService } from '../services/deps';
 import { FileService } from '../services/fs';
 import { getWorkspaceInformation } from './workspaceDependencies';
 
 export type { BundlerOptions } from '../build/types';
 
+// Detect runtime platform once at module load
+const BUNDLER_PLATFORM = getEsbuildPlatform();
```
Comment (wardpeet) [inline packages/deployer/src/bundler/index.ts]: should be moved to buildBundler in cli so other deployers can override

Comment (graysonhicks) [reply packages/deployer/src/bundler/index.ts]: update pushed

File: packages/cli/src/commands/build/BuildBundler.ts [hunk 2]
```diff
@@ -13,6 +13,7 @@ export class BuildBundler extends Bundler {
   constructor({ studio }: { studio?: boolean } = {}) {
     super('Build');
     this.studio = studio ?? false;
+    this.platform = getEsbuildPlatform();
```
Comment (wardpeet) [inline packages/cli/src/commands/build/BuildBundler.ts]: Let's just inline the function here. or make it part of  cli, no need to be in the deployer

**Review by wardpeet — APPROVED** [review]
