### PR TITLE
fixed issue with missing traceId with aisdk output format

### LINKED ISSUE #8113: [DISCORD:1419984871412990013] Traces ofstructured output parser end up in different tracing context
This issue was created from Discord post: https://discord.com/channels/1309558646228779139/1419984871412990013

This report is about Langfuse AI tracing specifically. I have a workflow step, and use the steps `tracingContext` to call an agent's `generateVNext`, the agent's span is nicely put within the workflow tracing context in Langfuse. However, if you use structured output, the trace ends up as a seperate trace in Langfuse. I would prefer (and I think most if not all people would) if the structured output parser trace ended up within the context of the agent run span

### PR DESCRIPTION
**Pull request by epinzur**
## Description

Fixes issue with missing traceId output when using `aisdk` output format

Also disables tracing in all input/output processors (so they don't appear as separate traces until we specifically want to include them in the trace output).

## Related Issue(s)

#6773 

Fixes #8113 and #8195

## Type of Change

- [X] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Code refactoring
- [ ] Performance improvement
- [ ] Test update

## Checklist

- [ ] I have made corresponding changes to the documentation (if applicable)
- [X] have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: packages/core/src/processors/processors/language-detector.ts [hunk 1]
```diff
@@ -172,6 +173,7 @@ export class LanguageDetector implements Processor {
       name: 'language-detector',
       instructions: options.instructions || this.createDefaultInstructions(),
       model: options.model,
+      options: { tracingPolicy: { internal: InternalSpans.ALL } },
```
Comment (epinzur) [inline packages/core/src/processors/processors/language-detector.ts:176]: this disables trace output for the agent.

or really marks it "internal", which is the equivalent as disabled for now.

**Review by wardpeet — APPROVED** [review]
