### PR TITLE
fix: persist data-* chunks to memory storage (#10477, #10582, #10936)

### LINKED ISSUE #10477: Persist data- events in mastra
This issue was created from Discord post 1442841150250811515:

[Open in Discord](https://discord.com/channels/1309558646228779139/1442841150250811515)

My setup leverages `chatRoute` and `useChat` from `ai-sdk`, i use `data-` partial events to expose deeply nested workflow step updates all the way to the supervisory agent stream generative UI.

But upon fetching messages from storage and converting to `UIMessages` i don't see the emitted events persisted and hence the components are not rendered when i refresh the chat.

I'm on v1 beta

### LINKED ISSUE #10936: How can I store custom parts with mastra mongodb storage
This issue was created from Discord post 1446411042447032411:

[Open in Discord](https://discord.com/channels/1309558646228779139/1446411042447032411)

Hello, i want my user can attach file-reference ( not attachment directly ) 

```parts: [
                        ...message.parts,
                        ...(attachments
                            ? attachments.map((attachment) => ({
                                    type: 'file-reference',
                                    fileId: attachment.fileId,
                                    fileName: attachment.fileName
                                }))
                            : [])
                    ]```

But the parts "file-reference" is not stored in mongodb .How can i achieve this ?

### PR DESCRIPTION
**Pull request by NikAiyer**
## Description

- Persist custom data chunks (`data-*` parts) from `writer.custom()` to memory storage
- Data chunks now survive page refreshes instead of only streaming to clients
- Update `@assistant-ui/react` to v0.11.47 with native `DataMessagePart` support
- Convert `data-*` parts to `DataMessagePart` format (`{ type: 'data', name: string, data: T }`)

### Core (`@mastra/core`)
- Intercept `data-*` chunks in `workflowLoopStream()` and persist to `messageList`
- Add `DataUIPart` to `MastraMessagePart` type in message-list
- Create `filterDataParts()` helper for V4 message compatibility
- Update cache key generation to handle data parts

### React SDK (`@mastra/react`)
- Convert `data-*` parts to `DataMessagePart` format in `toAssistantUIMessage`
- Update `@assistant-ui/react` from `0.10.45` to `0.11.47`

### Playground UI (`@mastra/playground-ui`)
- Update all `@assistant-ui/*` packages to compatible versions
- Fix breaking API changes (`getAttachmentAccept()` → `getState().attachmentAccept`)
- Add required `resume` prop to `ToolFallback`

## Related Issue(s)

Closes #10477
Closes #10936

## Type of Change

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Code refactoring
- [ ] Performance improvement
- [ ] Test update

## Checklist

- [ ] I have made corresponding changes to the documentation (if applicable)
- [ ] I have added tests that prove my fix is effective or that my feature works

## Summary by CodeRabbit

* **New Features**
  * data-* chunks are now persisted in memory, converted to native DataMessagePart shape, accumulate across chunks and survive refreshes.

* **Tests**
  * Added extensive tests for conversion, accumulation, metadata preservation, immutability, negative cases, end-to-end persistence, and recall.

* **Chores**
  * Updated UI-related package versions to enable native DataMessagePart support.

* **Bug Fixes**
  * Composer attachment accept handling now respects configured accept values.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: packages/playground-ui/src/components/assistant-ui/hooks/use-composer-add-attachment.ts [hunk 1]
```diff
@@ -48,7 +48,7 @@ export const useComposerAddAttachment = ({
     };
 
     input.click();
-  }, [composerRuntime, multiple]);
+  }, [composerRuntime, multiple, onChange]);
```
Comment (mfrachet) [inline packages/playground-ui/src/components/assistant-ui/hooks/use-composer-add-attachment.ts]: we should remove that. I'm fearing that onChange does not have a stable reference. If you encountered an issue because of that, please let me know, but otherwise, I think we should remove this onChange from the array here

Comment (NikAiyer) [reply packages/playground-ui/src/components/assistant-ui/hooks/use-composer-add-attachment.ts]: Ok will remove that from here.

**Review by mfrachet — APPROVED** [review]

**Review by abhiaiyer91 — APPROVED** [review]
