### PR TITLE
fix: add time-to-first-token (TTFT) support for Langfuse integration

### LINKED ISSUE #9444: [DISCORD:1433005133951664179] langfuse/mastra integration - time to first token data is missing
This issue was created from Discord post: https://discord.com/channels/1309558646228779139/1433005133951664179

Hi, i have an agent built using matra, and i have integrated it with langfuse for observability.
In langfuse im trying to see the "time to first token" metric but i get only 0 there.
Other metrics seem to work fine.
is this issue on mastra's side or did i integrated in a wrong way?

### PR DESCRIPTION
**Pull request by abhiaiyer91**
Fixes #9444

Previously, Langfuse showed 0 for the "time to first token" metric because we weren't setting `completionStartTime` on generation spans.

This adds `completionStartTime` to model generation spans. The timestamp is captured automatically when the first content chunk arrives during streaming (text, reasoning, tool-call, or object chunks).

```typescript
// Before: TTFT always showed 0 in Langfuse
// After: TTFT is calculated from completionStartTime - startTime
const result = await agent.stream('Hello');
```

Changes:
- Added `completionStartTime` field to `ModelGenerationAttributes`
- Updated Langfuse exporter to include `completionStartTime` as a top-level field
- Added first-chunk timestamp capture in `ModelSpanTracker`

## Release Notes

* **New Features**
  * Added time-to-first-token (TTFT) support for Langfuse observability. Streaming model responses now automatically capture the timestamp when the first token arrives, enabling precise TTFT metrics within Langfuse for performance monitoring.

* **Tests**
  * Added comprehensive test coverage for TTFT functionality, validating automatic timestamp capture in streaming responses and proper behavior for non-streaming generation scenarios.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: observability/mastra/src/model-tracing.ts [hunk 1]
```diff
@@ -317,24 +336,40 @@ export class ModelSpanTracker {
             case 'text-start':
             case 'text-delta':
             case 'text-end':
+              // Capture completion start time on first text content
+              if (chunk.type === 'text-delta') {
```
Comment (abhiaiyer91) [inline observability/mastra/src/model-tracing.ts:340]: I dont think these are the right places, im going to adjust them

Comment (epinzur) [reply observability/mastra/src/model-tracing.ts:340]: can we just do this on the first chunk, independent of chunk type? Like on line 333?

**Review by epinzur — APPROVED** [review]
