### PR TITLE
fix(@mastra/core): resolve OpenAI reasoning model memory issue on sec…

### LINKED ISSUE #11481: [BUG] OpenAI reasoning model + memory: second generate fails with missing item
### Describe the Bug

When using an OpenAI reasoning model with Memory enabled, the second agent.generate fails with: Item 'rs_...' of type 'reasoning' was provided without its required following item. It looks like the follow-up item for the reasoning part is missing when the memory is replayed.

Suspected cause: providerMetadata (openai.itemId=msg_...) arrives on `text-start`, but `processOutputStream` doesn’t persist it into runState. If `text-delta`/`text-end` lack providerMetadata, the flush uses `undefined`, so the stored text part misses the msg_ itemId. When memory is replayed, only the reasoning rs_ reference remains, triggering the error. (This seems different from the rs_ leakage fix (#11380); here it’s the msg_ itemId that never gets stored.)

### Steps To Reproduce

Using the minimal reproducible example

1. npm install
2. Set OPENAI_API_KEY in .env
3. npm run repro
4. The second agent.generate call throws the error above

[execution-log.txt](https://github.com/user-attachments/files/24377695/execution-log.txt)

### Link to Minimal Reproducible Example

https://github.com/kinoh/mastra-reasoning-bug-reproduction

### Expected Behavior

- The second agent.generate should succeed and continue the conversation using memory.

### Environment Information

```block
LLM Provider: OpenAI

$ npx envinfo --system --browsers --binaries --npmPackages --npmGlobalPackages
  System:
    OS: Linux 6.6 Ubuntu 24.04.1 LTS 24.04.1 LTS (Noble Numbat)
    CPU: (16) x64 AMD Ryzen 7 7735HS with Radeon Graphics
    Memory: 9.34 GB / 15.01 GB
    Container: Yes
    Shell: 5.2.21 - /bin/bash
  Binaries:
    Node: 24.9.0 - /home/<reducted>/.local/share/mise/installs/node/24.9.0/bin/node
    npm: 11.6.0 - /home/<reducted>/.local/share/mise/installs/node/24.9.0/bin/npm
    pnpm: 10.26.2 - /home/<reducted>/.local/share/pnpm/pnpm
  npmPackages:
    @mastra/core: 1.0.0-beta.19 => 1.0.0-beta.19
    @mastra/evals: 1.0.0-beta.3 => 1.0.0-beta.3
    @mastra/libsql: 1.0.0-beta.10 => 1.0.0-beta.10
    @mastra/loggers: 1.0.0-beta.3 => 1.0.0-beta.3
    @mastra/memory: 1.0.0-beta.10 => 1.0.0-beta.10
    @types/node: ^25.0.3 => 25.0.3
    mastra: 1.0.0-beta.12 => 1.0.0-beta.12
    tsx: ^4.21.0 => 4.21.0
    typescript: ^5.9.3 => 5.9.3
    zod: ^4.2.1 => 4.2.1
  npmGlobalPackages:
    @anthropic-ai/claude-code: 2.0.76
    @openai/codex: 0.77.0
    corepack: 0.34.0
    npm: 11.6.0
```

### Verification

- [x] I have searched the existing issues to make sure this is not a duplicate
- [x] I have included sufficient information for the team to reproduce and understand the issue

### PR DESCRIPTION
**Pull request by roaminro**
## Description

…ond generate call

This commit addresses a bug where the second `agent.generate()` call with OpenAI reasoning models would fail due to missing `providerMetadata` for text parts. The fix ensures that `text-start` events correctly capture the `msg_` itemId, allowing for proper memory replay and preventing errors related to missing required items.

Additionally, comprehensive tests have been added to validate the fix and ensure that both reasoning and text parts retain their respective itemIds during interactions.

## Related Issue(s)

Fixes #11481.

## Type of Change

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Code refactoring
- [ ] Performance improvement
- [ ] Test update

## Checklist

- [ ] I have made corresponding changes to the documentation (if applicable)
- [x] I have added tests that prove my fix is effective or that my feature works

## Summary by CodeRabbit

* **Bug Fixes**
  * Resolved memory replay mismatch by correctly capturing text-part provider metadata on stream start and clearing it on stream end, preventing ID leakage between reasoning and text parts.
  * Ensures generate and follow-up flows include distinct metadata for reasoning and text segments.

* **Tests**
  * Added unit and integration tests covering metadata capture/propagation across streaming, generate, tool-call, replay flows, and compatibility with the newer response-item reference format.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

**Review by abhiaiyer91 — APPROVED** [review]

File: packages/core/src/loop/workflows/agentic-execution/llm-execution-step.ts [hunk 1]
```diff
@@ -139,6 +139,23 @@ async function processOutputStream<OUTPUT extends OutputSchema = undefined>({
...
         break;
 
+      case 'text-start': {
+        // Capture text-start's providerMetadata (e.g., openai.itemId: "msg_xxx")
+        // This is needed because, for example, OpenAI reasoning models send separate itemIds for
+        // reasoning (rs_xxx) and text (msg_xxx) parts. The text's itemId must be
+        // preserved so that when memory is replayed, OpenAI sees the required
+        // following item for the reasoning part.
+        if (chunk.payload.providerMetadata) {
+          runState.setState({
```
Comment (abhiaiyer91) [inline packages/core/src/loop/workflows/agentic-execution/llm-execution-step.ts:153]: text end will need to unset this then!
