### PR TITLE
fix(deployer): Windows paths

### LINKED ISSUE #11508: [BUG] node-modules-extension-resolver didn't work on Windows
### Describe the Bug

just run `pnpm dev` results to a

```
TypeError [ERR_INVALID_URL_SCHEME]: The URL must be of scheme file
    at fileURLToPath (node:internal/url:1608:11)
    at fileURLToPath (file:///D:/Demos/Demo1/node_modules/.pnpm/mlly@1.8.0/node_modules/mlly/dist/index.mjs:1970:25)
    at pathToFileURL (file:///D:/Demos/Demo1/node_modules/.pnpm/mlly@1.8.0/node_modules/mlly/dist/index.mjs:1973:26)
    at _resolve (file:///D:/Demos/Demo1/node_modules/.pnpm/mlly@1.8.0/node_modules/mlly/dist/index.mjs:2107:10)
    at resolveSync (file:///D:/Demos/Demo1/node_modules/.pnpm/mlly@1.8.0/node_modules/mlly/dist/index.mjs:2110:10)
    at resolvePathSync (file:///D:/Demos/Demo1/node_modules/.pnpm/mlly@1.8.0/node_modules/mlly/dist/index.mjs:2120:24)
    at _resolve (file:///D:/Demos/Demo1/node_modules/.pnpm/local-pkg@1.1.2/node_modules/local-pkg/dist/index.mjs:80:22)
    at resolvePackage (file:///D:/Demos/Demo1/node_modules/.pnpm/local-pkg@1.1.2/node_modules/local-pkg/dist/index.mjs:133:12)
    at getPackageJsonPath (file:///D:/Demos/Demo1/node_modules/.pnpm/local-pkg@1.1.2/node_modules/local-pkg/dist/index.mjs:104:17)
    at file:///D:/Demos/Demo1/node_modules/.pnpm/local-pkg@1.1.2/node_modules/local-pkg/dist/index.mjs:114:27
    at Generator.next (<anonymous>)
    at iterateAsync (file:///D:/Demos/Demo1/node_modules/.pnpm/quansync@0.2.11/node_modules/quansync/dist/index.mjs:63:27)
    at async (file:///D:/Demos/Demo1/node_modules/.pnpm/quansync@0.2.11/node_modules/quansync/dist/index.mjs:77:14)
    at iter.then (file:///D:/Demos/Demo1/node_modules/.pnpm/quansync@0.2.11/node_modules/quansync/dist/index.mjs:23:48) {
  code: 'ERR_INVALID_URL_SCHEME'
}
TypeError [ERR_INVALID_URL_SCHEME]: The URL must be of scheme file
    at fileURLToPath (node:internal/url:1608:11)
    at fileURLToPath (file:///D:/Demos/Demo1/node_modules/.pnpm/mlly@1.8.0/node_modules/mlly/dist/index.mjs:1970:25)
    at pathToFileURL (file:///D:/Demos/Demo1/node_modules/.pnpm/mlly@1.8.0/node_modules/mlly/dist/index.mjs:1973:26)
    at _resolve (file:///D:/Demos/Demo1/node_modules/.pnpm/mlly@1.8.0/node_modules/mlly/dist/index.mjs:2107:10)
    at resolveSync (file:///D:/Demos/Demo1/node_modules/.pnpm/mlly@1.8.0/node_modules/mlly/dist/index.mjs:2110:10)
    at resolvePathSync (file:///D:/Demos/Demo1/node_modules/.pnpm/mlly@1.8.0/node_modules/mlly/dist/index.mjs:2120:24)
    at _resolve (file:///D:/Demos/Demo1/node_modules/.pnpm/local-pkg@1.1.2/node_modules/local-pkg/dist/index.mjs:80:22)
    at resolvePackage (file:///D:/Demos/Demo1/node_modules/.pnpm/local-pkg@1.1.2/node_modules/local-pkg/dist/index.mjs:133:12)
    at getPackageJsonPath (file:///D:/Demos/Demo1/node_modules/.pnpm/local-pkg@1.1.2/node_modules/local-pkg/dist/index.mjs:104:17)
    at file:///D:/Demos/Demo1/node_modules/.pnpm/local-pkg@1.1.2/node_modules/local-pkg/dist/index.mjs:114:27
    at Generator.next (<anonymous>)
    at iterateAsync (file:///D:/Demos/Demo1/node_modules/.pnpm/quansync@0.2.11/node_modules/quansync/dist/index.mjs:63:27)
    at async (file:///D:/Demos/Demo1/node_modules/.pnpm/quansync@0.2.11/node_modules/quansync/dist/index.mjs:77:14)
    at iter.then (file:///D:/Demos/Demo1/node_modules/.pnpm/quansync@0.2.11/node_modules/quansync/dist/index.mjs:23:48) {
  code: 'ERR_INVALID_URL_SCHEME'
}
Error: Package D: not found
    at getPackageJSON (file:///D:/Demos/Demo1/node_modules/.pnpm/@mastra+deployer@1.0.0-beta_aac6778e476e472e2d2842760f45ff5b/node_modules/@mastra/deployer/dist/chunk-EGNU46SF.js:16:11)
    at async Object.resolveId (file:///D:/Demos/Demo1/node_modules/.pnpm/@mastra+deployer@1.0.0-beta_aac6778e476e472e2d2842760f45ff5b/node_modules/@mastra/deployer/dist/chunk-EGNU46SF.js:39:29)
    at async PluginDriver.hookFirstAndGetPlugin (file:///D:/Demos/Demo1/node_modules/.pnpm/rollup@4.50.2/node_modules/rollup/dist/es/shared/node-entry.js:22310:28)
    at async resolveId (file:///D:/Demos/Demo1/node_modules/.pnpm/rollup@4.50.2/node_modules/rollup/dist/es/shared/node-entry.js:20787:26)
    at async ModuleLoader.resolveId (file:///D:/Demos/Demo1/node_modules/.pnpm/rollup@4.50.2/node_modules/rollup/dist/es/shared/node-entry.js:21223:15)
    at async Object.resolveId (file:///D:/Demos/Demo1/node_modules/.pnpm/@mastra+deployer@1.0.0-beta_aac6778e476e472e2d2842760f45ff5b/node_modules/@mastra/deployer/dist/chunk-BDA7RMRF.js:203:27)
    at async PluginDriver.hookFirstAndGetPlugin (file:///D:/Demos/Demo1/node_modules/.pnpm/rollup@4.50.2/node_modules/rollup/dist/es/shared/node-entry.js:22310:28)
    at async resolveId (file:///D:/Demos/Demo1/node_modules/.pnpm/rollup@4.50.2/node_modules/rollup/dist/es/shared/node-entry.js:20787:26)
    at async ModuleLoader.resolveId (file:///D:/Demos/Demo1/node_modules/.pnpm/rollup@4.50.2/node_modules/rollup/dist/es/shared/node-entry.js:21223:15)
    at async Object.resolveId (file:///D:/Demos/Demo1/node_modules/.pnpm/@rollup+plugin-commonjs@29.0.0_rollup@4.50.2/node_modules/@rollup/plugin-commonjs/dist/es/index.js:617:10)
    at async PluginDriver.hookFirstAndGetPlugin (file:///D:/Demos/Demo1/node_modules/.pnpm/rollup@4.50.2/node_modules/rollup/dist/es/shared/node-entry.js:22310:28)
    at async resolveId (file:///D:/Demos/Demo1/node_modules/.pnpm/rollup@4.50.2/node_modules/rollup/dist/es/shared/node-entry.js:20787:26)
    at async ModuleLoader.resolveId (file:///D:/Demos/Demo1/node_modules/.pnpm/rollup@4.50.2/node_modules/rollup/dist/es/shared/node-entry.js:21223:15)
    at async PluginDriver.hookFirstAndGetPlugin (file:///D:/Demos/Demo1/node_modules/.pnpm/rollup@4.50.2/node_modules/rollup/dist/es/shared/node-entry.js:22310:28)
    at async resolveId (file:///D:/Demos/Demo1/node_modules/.pnpm/rollup@4.50.2/node_modules/rollup/dist/es/shared/node-entry.js:20787:26)
    at async ModuleLoader.resolveId (file:///D:/Demos/Demo1/node_modules/.pnpm/rollup@4.50.2/node_modules/rollup/dist/es/shared/node-entry.js:21223:15)
    at async Object.resolveId (file:///D:/Demos/Demo1/node_modules/.pnpm/@rollup+plugin-commonjs@29.0.0_rollup@4.50.2/node_modules/@rollup/plugin-commonjs/dist/es/index.js:617:10)
    at async PluginDriver.hookFirstAndGetPlugin (file:///D:/Demos/Demo1/node_modules/.pnpm/rollup@4.50.2/node_modules/rollup/dist/es/shared/node-entry.js:22310:28)
    at async resolveId (file:///D:/Demos/Demo1/node_modules/.pnpm/rollup@4.50.2/node_modules/rollup/dist/es/shared/node-entry.js:20787:26)
    at async ModuleLoader.resolveId (file:///D:/Demos/Demo1/node_modules/.pnpm/rollup@4.50.2/node_modules/rollup/dist/es/shared/node-entry.js:21223:15)
    at async file:///D:/Demos/Demo1/node_modules/.pnpm/rollup@4.50.2/node_modules/rollup/dist/es/shared/node-entry.js:21527:50
Error: Package D: not found
    at getPackageJSON (file:///D:/Demos/Demo1/node_modules/.pnpm/@mastra+deployer@1.0.0-beta_aac6778e476e472e2d2842760f45ff5b/node_modules/@mastra/deployer/dist/chunk-EGNU46SF.js:16:11)
    at async Object.resolveId (file:///D:/Demos/Demo1/node_modules/.pnpm/@mastra+deployer@1.0.0-beta_aac6778e476e472e2d2842760f45ff5b/node_modules/@mastra/deployer/dist/chunk-EGNU46SF.js:39:29)
    at async PluginDriver.hookFirstAndGetPlugin (file:///D:/Demos/Demo1/node_modules/.pnpm/rollup@4.50.2/node_modules/rollup/dist/es/shared/node-entry.js:22310:28)
    at async resolveId (file:///D:/Demos/Demo1/node_modules/.pnpm/rollup@4.50.2/node_modules/rollup/dist/es/shared/node-entry.js:20787:26)
    at async ModuleLoader.resolveId (file:///D:/Demos/Demo1/node_modules/.pnpm/rollup@4.50.2/node_modules/rollup/dist/es/shared/node-entry.js:21223:15)
    at async Object.resolveId (file:///D:/Demos/Demo1/node_modules/.pnpm/@mastra+deployer@1.0.0-beta_aac6778e476e472e2d2842760f45ff5b/node_modules/@mastra/deployer/dist/chunk-BDA7RMRF.js:203:27)
    at async PluginDriver.hookFirstAndGetPlugin (file:///D:/Demos/Demo1/node_modules/.pnpm/rollup@4.50.2/node_modules/rollup/dist/es/shared/node-entry.js:22310:28)
    at async resolveId (file:///D:/Demos/Demo1/node_modules/.pnpm/rollup@4.50.2/node_modules/rollup/dist/es/shared/node-entry.js:20787:26)
    at async ModuleLoader.resolveId (file:///D:/Demos/Demo1/node_modules/.pnpm/rollup@4.50.2/node_modules/rollup/dist/es/shared/node-entry.js:21223:15)
    at async Object.resolveId (file:///D:/Demos/Demo1/node_modules/.pnpm/@rollup+plugin-commonjs@29.0.0_rollup@4.50.2/node_modules/@rollup/plugin-commonjs/dist/es/index.js:617:10)
    at async PluginDriver.hookFirstAndGetPlugin (file:///D:/Demos/Demo1/node_modules/.pnpm/rollup@4.50.2/node_modules/rollup/dist/es/shared/node-entry.js:22310:28)
    at async resolveId (file:///D:/Demos/Demo1/node_modules/.pnpm/rollup@4.50.2/node_modules/rollup/dist/es/shared/node-entry.js:20787:26)
    at async ModuleLoader.resolveId (file:///D:/Demos/Demo1/node_modules/.pnpm/rollup@4.50.2/node_modules/rollup/dist/es/shared/node-entry.js:21223:15)
    at async PluginDriver.hookFirstAndGetPlugin (file:///D:/Demos/Demo1/node_modules/.pnpm/rollup@4.50.2/node_modules/rollup/dist/es/shared/node-entry.js:22310:28)
    at async resolveId (file:///D:/Demos/Demo1/node_modules/.pnpm/rollup@4.50.2/node_modules/rollup/dist/es/shared/node-entry.js:20787:26)
    at async ModuleLoader.resolveId (file:///D:/Demos/Demo1/node_modules/.pnpm/rollup@4.50.2/node_modules/rollup/dist/es/shared/node-entry.js:21223:15)
    at async Object.resolveId (file:///D:/Demos/Demo1/node_modules/.pnpm/@rollup+plugin-commonjs@29.0.0_rollup@4.50.2/node_modules/@rollup/plugin-commonjs/dist/es/index.js:617:10)
    at async PluginDriver.hookFirstAndGetPlugin (file:///D:/Demos/Demo1/node_modules/.pnpm/rollup@4.50.2/node_modules/rollup/dist/es/shared/node-entry.js:22310:28)
    at async resolveId (file:///D:/Demos/Demo1/node_modules/.pnpm/rollup@4.50.2/node_modules/rollup/dist/es/shared/node-entry.js:20787:26)
    at async ModuleLoader.resolveId (file:///D:/Demos/Demo1/node_modules/.pnpm/rollup@4.50.2/node_modules/rollup/dist/es/shared/node-entry.js:21223:15)
    at async file:///D:/Demos/Demo1/node_modules/.pnpm/rollup@4.50.2/node_modules/rollup/dist/es/shared/node-entry.js:21527:50
```

### Steps To Reproduce

run `https://github.com/mastra-ai/template-coding-agent` on a Windows machine, upgrade all deps to `beta`

### Link to Minimal Reproducible Example

https://github.com/mastra-ai/template-coding-agent

### Expected Behavior

nr dev works correctly

### Environment Information

```block
System:
    OS: Windows 11 10.0.26200
    CPU: (16) x64 AMD Ryzen 7 9700X 8-Core Processor
    Memory: 21.88 GB / 61.66 GB
  Binaries:
    Node: 22.18.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - C:\Program Files\nodejs\yarn.CMD
    npm: 11.6.4 - C:\Program Files\nodejs\npm.CMD
    pnpm: 10.26.2 - C:\Program Files\nodejs\pnpm.CMD
    bun: 1.3.5 - C:\Users\Admin\AppData\Roaming\npm\bun.CMD
  Browsers:
    Chrome: 143.0.7499.170
    Edge: Chromium (140.0.3485.54)
  npmPackages:
    @ai-sdk/openai: ^3.0.2 => 3.0.2 
    @e2b/code-interpreter: ^2.3.3 => 2.3.3 
    @mastra/core: 1.0.0-beta.19 => 1.0.0-beta.19 
    @mastra/deployer: 1.0.0-beta.19 => 1.0.0-beta.19 
    @mastra/fastembed: 1.0.0-beta.2 => 1.0.0-beta.2 
    @mastra/libsql: 1.0.0-beta.10 => 1.0.0-beta.10 
    @mastra/loggers: 1.0.0-beta.3 => 1.0.0-beta.3 
    @mastra/mcp: 1.0.0-beta.7 => 1.0.0-beta.7 
    @mastra/memory: 1.0.0-beta.10 => 1.0.0-beta.10 
    @mastra/observability: 1.0.0-beta.9 => 1.0.0-beta.9 
    @types/fs-extra: ^11.0.4 => 11.0.4
    @types/node: ^25.0.3 => 25.0.3
    axios: ^1.13.2 => 1.13.2
    fs-extra: ^11.3.3 => 11.3.3
    mastra: 1.0.0-beta.12 => 1.0.0-beta.12
    typescript: ^5.9.3 => 5.9.3
    zod: ^3 => 3.25.76
  npmGlobalPackages:
    @antfu/ni: 25.0.0
    @anthropic-ai/claude-code: 2.0.76
    @benborla29/mcp-server-mysql: 2.0.5
    @e2b/cli: 2.4.2
    @google/gemini-cli: 0.22.2
    @nestjs/cli: 11.0.10
    @openai/codex: 0.75.0
    bun: 1.3.5
    claude-code-wakatime: 2.2.0
    clinic: 13.0.0
    cross-env: 10.0.0
    generator-office: 3.0.2
    npm: 11.6.4
    opencode-ai: 1.0.200
    redis-cli: 2.1.2
    web-push: 3.6.7
    yo: 6.0.0
```

### Verification

- [x] I have searched the existing issues to make sure this is not a duplicate
- [x] I have included sufficient information for the team to reproduce and understand the issue

### PR DESCRIPTION
**Pull request by LekoArts**
## Description

- Get `pnpm build` on windows machine working
- Fix the node-modules-resolver by checking with `isAbsolute` so that windows `C:` paths are not looked at

## Related Issue(s)

Fixes #11508

## Type of Change

- [X] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Code refactoring
- [ ] Performance improvement
- [ ] Test update

## Checklist

- [ ] I have made corresponding changes to the documentation (if applicable)
- [ ] I have added tests that prove my fix is effective or that my feature works

## Summary by CodeRabbit

* **Bug Fixes**
  * Fixed module resolution to skip absolute Windows-style paths and corrected node_modules checking on Windows.

* **Tests**
  * Added test coverage for absolute Windows paths.

* **Documentation**
  * Updated contributing guide links.

* **Chores**
  * Removed a configuration file, adjusted project ignore patterns, and improved internal path resolution and type safety across packages.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: packages/deployer/src/build/plugins/node-modules-extension-resolver.ts [hunk 1]
```diff
@@ -35,7 +35,7 @@ export function nodeModulesExtensionResolver(): Plugin {
     name: 'node-modules-extension-resolver',
     async resolveId(id, importer, options) {
       // Skip relative imports, absolute paths, no importer, or builtin modules
-      if (!importer || id.startsWith('.') || id.startsWith('/') || isBuiltinModule(id)) {
+      if (!importer || id.startsWith('.') || id.startsWith('/') || isBuiltinModule(id) || isAbsolute(id)) {
```
Comment (LekoArts) [inline packages/deployer/src/build/plugins/node-modules-extension-resolver.ts:38]: The actual fix

**Review by graysonhicks — APPROVED** [review]
