### PR TITLE
fix: insert step-start between consecutive loop iterations

### LINKED ISSUE #14124: [BUG] Consecutive tool-only turns are incorrectly merged into one
### Describe the Bug

When an agent performs two consecutive turns with only tool calls (no output text, thinking) those tool calls are merged into a single turn instead of being kept separate.

This leads the agent to the false assumption that it ran all the tools in parallel, which can affect its output in subsequent messages.

For example, here the agent thinks it ran the tools in parallel:

Image

But it didn't:

Image

You can see here why it is getting it wrong - mastra has merged the two turns into one when it sends subsequent LLM calls:

```json
{
      "role": "assistant",
      "content": [
        {
          "type": "tool-call",
          "toolCallId": "toolu_01NtUVX3zKx3DKpZLxZVdNPM",
          "toolName": "weatherTool",
          "input": {
            "location": "London"
          }
        },
        {
          "type": "tool-call",
          "toolCallId": "toolu_012a27zjYRaLbugehnFGmVM6",
          "toolName": "weatherTool",
          "input": {
            "location": "Paris"
          }
        }
      ]
    },
    {
      "role": "tool",
      "content": [
        {
          "type": "tool-result",
          "toolCallId": "toolu_01NtUVX3zKx3DKpZLxZVdNPM",
          "toolName": "weatherTool",
          "output": {
            "type": "json",
            "value": {
              "temperature": 10,
              "feelsLike": 7.4,
              "humidity": 95,
              "windSpeed": 16.2,
              "windGust": 34.9,
              "conditions": "Light drizzle",
              "location": "London"
            }
          },
          "input": "[Circular]"
        },
        {
          "type": "tool-result",
          "toolCallId": "toolu_012a27zjYRaLbugehnFGmVM6",
          "toolName": "weatherTool",
          "output": {
            "type": "json",
            "value": {
              "temperature": 11,
              "feelsLike": 8.2,
              "humidity": 81,
              "windSpeed": 15,
              "windGust": 32.4,
              "conditions": "Overcast",
              "location": "Paris"
            }
          },
          "input": "[Circular]"
        }
      ]
    },
    {
      "role": "user",
      "content": [
        {
          "type": "text",
          "text": "Did you run them in separate turns or in parallel?"
        }
      ]
    }
```

It may not be immediately obvious why this is so problematic. Here's a motivating example: I had an agent with two tools - query data, and reply to user. It would query the data, then reply as two separate turns. Then it would incorrectly see it did the query and reply in parallel, and reply again "correcting" itself with the actual updated (but actually identical) data.

### Steps To Reproduce

Create a new project.

Send the weather agent this message: "Do not say anything. Just run your tool once, see the result but do not say anything, and then run the tool again"

Then ask it if it ran the tools in parallel - it will answer yes

However, check the actual LLM calls using observability: It ran them as separate turns

### Link to Minimal Reproducible Example

Reproducible with default-project weather agent

### Expected Behavior

Mastra should leave the two assistant turns as separate turns, instead of condensing them into one.

### Environment Information

```block
Claude sonnet 4.6 (but any will do)
```

### Verification

- [x] I have searched the existing issues to make sure this is not a duplicate
- [x] I have included sufficient information for the team to reproduce and understand the issue

### PR DESCRIPTION
**Pull request by CalebBarnes**
## Problem

When the agentic loop runs multiple iterations that each produce only tool calls, they get merged into a single assistant message with no boundary. The LLM then misinterprets sequential tool calls as parallel calls from a single turn.

This was reported in [#14124](https://github.com/mastra-ai/mastra/issues/14124).

## Root cause

`MessageMerger` merges consecutive assistant messages that share the same `messageId`. Since `messageId` is generated once per `agent.stream()` call and reused across all loop iterations, tool-only turns from different iterations collapse into a single message block.

## Fix

- Add `messageList.stepStart()` — finds the most recent unsealed assistant message and appends a `{ type: 'step-start' }` part, handling source migration for persistence.
- Call `messageList.stepStart()` at the start of each loop iteration after the first in `llm-execution-step.ts`.

This ensures `convertToModelMessages` splits them into separate blocks, so the LLM sees sequential steps rather than parallel tool calls.

## Changes

- `message-list.ts`: Added `stepStart()` method
- `llm-execution-step.ts`: Call `stepStart()` when `currentIteration > 1`
- `tools.ts`: Test with 3-iteration mock (tool → tool → text) verifying `step-start` boundary
- `options.ts`: Updated inline snapshot

## Test plan

```bash
cd packages/core
pnpm vitest run src/loop/loop.test.ts -t "step-start"
pnpm vitest run src/agent/__tests__/supervisor-integration.test.ts
pnpm vitest run --project unit:packages/core  # full suite: 5696 passed
```

## Summary by CodeRabbit

* **Bug Fixes**
  * Prevented consecutive tool-only iterations from being merged into a single assistant response by inserting explicit step-start boundaries, preserving sequential tool-call ordering.

* **Tests**
  * Added tests to verify step-start boundaries are inserted between consecutive tool-only iterations and that insertion is idempotent and respects sealed/invalid states.

* **Chores**
  * Added release metadata for a patch.

### CODE REVIEW

**Review by TylerBarnes — APPROVED** [review]
hell yea! 🔥

File: packages/core/src/loop/workflows/agentic-execution/llm-execution-step.ts [hunk 1]
```diff
@@ -642,6 +642,14 @@ export function createLLMExecutionStep<TOOLS extends ToolSet = ToolSet, OUTPUT =
     execute: async ({ inputData, bail, tracingContext }) => {
       currentIteration++;
 
+      // Insert a step-start boundary between loop iterations so that
+      // consecutive tool-only turns are not collapsed into a single block
+      // by convertToModelMessages. This ensures the LLM sees them as
+      // sequential steps rather than parallel tool calls.
+      if (currentIteration > 1) {
```
Comment (TylerBarnes) [inline packages/core/src/loop/workflows/agentic-execution/llm-execution-step.ts:649]: oh is this 1 indexed? I think first step is step 0 right?

Comment (TylerBarnes) [reply packages/core/src/loop/workflows/agentic-execution/llm-execution-step.ts:649]: nvm lol just had to expand the gh diff one time above haha

Comment (CalebBarnes) [reply packages/core/src/loop/workflows/agentic-execution/llm-execution-step.ts:649]: Yeah I think it starts at 0 `let currentIteration = 0;` but then this check is right after calling `currentIteration++` so it should be at least 1
