### PR TITLE
fix(core,memory): fix schema issues with certain model providers

### LINKED ISSUE #6548: [DISCORD:1400152363674763394] Invalid schema for function 'updateWorkingMemory'
This issue was created from Discord post: https://discord.com/channels/1309558646228779139/1400152363674763394

Full error message: An error occurred while processing your request. Invalid schema for function 'updateWorkingMemory': In context=('properties', 'newMemory', 'anyOf', '0', 'anyOf', '0', 'not'), schema must have a 'type' key.

No errors within the `mastra dev` terminal, this error is received by client.

Error occurs when using o4-mini, o1-mini.
Error **does not** show up when using gpt-4o-mini.

Error disappears when commenting this out:
```js
      workingMemory: {
        enabled: true,
        template: `Track user preferences and key details`,
        version: "vnext",
      },
```

Dependencies:
```json
  "dependencies": {
    "@ai-sdk/openai": "^1.3.23",
    "@mastra/core": "^0.11.1",
    "@mastra/deployer-vercel": "^0.11.8",
    "@mastra/libsql": "^0.11.2",
    "@mastra/memory": "^0.11.5",
    "@mastra/pinecone": "^0.11.1",
    "@mastra/rag": "^1.0.4",
    "ai": "^4.3.19",
    "emoji-regex": "^10.4.0",
    "zod": "^3.25.76"
  },
  "devDependencies": {
    "@types/node": "^24.1.0",
    "mastra": "^0.10.15",
    "typescript": "^5.8.3"
  }
```

### PR DESCRIPTION
**Pull request by DanielSLew**
## Description

openai reasoning models would not handle the new working memory tool schema properly and would throw an error. I discovered that the memory tools were not being run through the schema-compat, this is because we weren't using `makeCoreTool` on the memory tools. Adding this fixed the issue.

This fixes https://github.com/mastra-ai/mastra/issues/6548

### CODE REVIEW

File: packages/memory/src/tools/working-memory.ts [hunk 1]
```diff
@@ -51,19 +51,16 @@ export const __experimental_updateWorkingMemoryToolVNext = (config: MemoryConfig
     newMemory: z
       .string()
       .optional()
-      .nullable()
```
Comment (DanielSLew) [inline packages/memory/src/tools/working-memory.ts:54]: optional and nullable were redundant

**Review by wardpeet — APPROVED** [review]

File: packages/core/src/agent/index.ts [hunk 2]
```diff
@@ -879,71 +879,29 @@ export class Agent<
...
-                              resourceId: resourceId || '',
-                            },
-                            text: `[Agent:${this.name}] - Failed memory tool execution`,
-                          },
-                          err,
-                        );
-                        this.logger.trackException(mastraError);
-                        this.logger.error(mastraError.toString());
-                        throw mastraError;
-                      }
```
Comment (TylerBarnes) [inline packages/core/src/agent/index.ts:936]: don't we still need some of this? especially the MastraError

Comment (DanielSLew) [reply packages/core/src/agent/index.ts:936]: no, this all happens inside of makeCoreTool
