### PR TITLE
test(memory): add message ordering integration tests for Issue #9909

### LINKED ISSUE #9909: [BUG] Agent streaming: Text deltas lost and incorrect message ordering when persisting to storage
## Describe the Bug

When using `agent.stream()` with Mastra's storage integration, the persisted messages in the database have two critical issues:

1. **Missing text content**: Initial text-delta chunks before tool calls are lost during persistence.
2. **Incorrect ordering**: Text content that appears after tool execution during streaming is incorrectly placed before tool invocations in the stored message

This causes the UI to display different content when loading messages from storage versus during the initial stream, breaking the user experience on page reload.

### Example of the Issue

**During streaming (correct behavior):**
```
1. Text: "I'll create a bill of materials for 1000 liters..."
2. Tool calls: web_search (3 invocations)
3. Sources: (30 source citations)
4. Text: "Based on the market research, I now have..."
5. Tool call: createBom
6. Text: "Perfect! I've created a comprehensive bill..."
```

**After loading from DB (incorrect behavior):**
```
1. Text: "Based on the market research, I now have..." ❌ Wrong position
2. Tool calls: web_search (3 invocations)
3. Tool call: createBom
4. Text: "Perfect! I've created a comprehensive bill..."
```

Notice that:
- The first text paragraph is **completely missing**
- The "Based on the market research..." text (which came AFTER web_search during streaming) now appears BEFORE the tool calls
- Sources are not persisted (this may be intentional)

#### Screenshots
- Streamed message - full content and correct ordering
Image

- Loaded message from DB - missing paragraph and incorrect order
Image

### JSON Evidence

**Correct stream format** - from [message-streamed.json](https://github.com/user-attachments/files/23452132/message-streamed.json)

```json
[
    {
        "type": "text-delta",
        "runId": "0022735d-47af-4c4f-ab34-7460baa0c1b7",
        "from": "AGENT",
        "payload": { "id": "0", "text": "I'll create" }
    },
    {
        "type": "text-delta",
        "runId": "0022735d-47af-4c4f-ab34-7460baa0c1b7",
        "from": "AGENT",
        "payload": { "id": "0", "text": " a bill" }
    },
    // ... more id "0" text deltas
    {
        "type": "tool-call",
        "runId": "0022735d-47af-4c4f-ab34-7460baa0c1b7",
        "from": "AGENT",
        "payload": {
            "toolCallId": "srvtoolu_013nBrA76T4wDSxhEEYBVea8",
            "toolName": "web_search",
            // ...
        }
    },
    // ... sources
    {
        "type": "text-delta",
        "runId": "0022735d-47af-4c4f-ab34-7460baa0c1b7",
        "from": "AGENT",
        "payload": { "id": "7", "text": "Based" }
    },
    // ... more id "7" text deltas
]
```

**Incorrect DB format** - from [message-from-db.json](https://github.com/user-attachments/files/23452133/message-from-db.json)
```json
{
    "format": 2,
    "parts": [
        {
            "type": "text",
            "text": "Based on the market research, I now have the information needed to create a comprehensive BOM for 1000 liters of organic orange juice produced in Italy. Let me structure this with realistic data on juice extraction yields, organic orange sourcing, processing, and packaging.\n\nNow I'll create the bill of materials with the hierarchical structure reflecting the value chain stages:"
        },
        {
            "type": "tool-invocation",
            "toolInvocation": {
                "state": "result",
                "toolCallId": "srvtoolu_013nBrA76T4wDSxhEEYBVea8",
                "toolName": "web_search",
                // ...
            }
        },
        // ... more tool invocations, then final text
    ]
}
```

The first text paragraph ("I'll create a bill of materials...") is completely missing, and the ordering is wrong.

The issue appears to be in Mastra's internal logic for:
1. Grouping text-delta chunks by ID during stream-to-storage conversion
2. Determining the correct insertion point for text parts relative to tool invocations
3. Handling multiple text sequences with different IDs in a single agent response

This is a critical bug as it breaks conversation history and makes the application unusable after page reloads.

## Steps To Reproduce

1. Set up a Mastra agent as part of a Next.js project with:
   - Anthropic Claude model (with web_search tool enabled)
   - Custom tools that trigger multi-step workflows
   - LibSQL storage configured
   - Memory configured for thread/message persistence

2. Stream a message that:
   - Starts with text output
   - Invokes multiple tools (e.g., web_search)
   - Returns more text after tool execution
   - Invokes another tool
   - Ends with final text

3. Observe the correct output during streaming

4. Reload messages from storage using `storage.getMessages({ threadId, format: "v2" })`

5. Compare the loaded message structure with what was streamed

#### Agent Stream Setup (`src/app/api/chat-mastra/route.ts`)

- Using Vercel AI SDK route handler and `useChat` hook, as described in [Mastra Docs > Using Vercel AI SDK > Stream Transformations](https://mastra.ai/docs/frameworks/agentic-uis/ai-sdk#stream-transformations)

```typescript
// Get agent and stream
const agent = mastra.getAgent("chat");

const stream = await agent.stream(uiMessages, {
  runtimeContext,
  memory: {
    thread: id,
    resource: userId,
  },
  maxSteps: 5,
  onChunk(chunk) {
    console.log(JSON.stringify(chunk, null, 2));
  },
});

if (!stream) {
  return new Response("Failed to get stream", { status: 500 });
}

// Transform stream into AI SDK format
const uiMessageStream = createUIMessageStream({
  execute: async ({ writer }) => {
    for await (const part of toAISdkFormat(stream, { from: "agent" })!) {
      writer.write(part);
    }
  },
});

return createUIMessageStreamResponse({ stream: uiMessageStream });
```

#### Agent Definition (`src/mastra/agents/chat.ts`)

```typescript
import { Agent } from "@mastra/core/agent";
import { Memory } from "@mastra/memory";
import { Models, Tools } from "../models/models";
import { createBomTool } from "../tools/create-bom";
// ... other imports

export const chat = new Agent({
  name: "chat",
  model: Models.claudeSonnet45,
  tools: {
    web_search: Tools.anthropicWebSearchTool,
    createBom: createBomTool,
    // ... other tools
  },
  memory: new Memory(),
  instructions: ({ runtimeContext }) => {
    // Dynamic instructions based on runtime context
    return systemMessages(
      selectedChatMode,
      currency,
      conversionRate,
      referenceMaterials,
      latestBomArtifact
    );
  },
});
```

#### Mastra Instance (`src/mastra/index.ts`)

```typescript
import { Mastra } from "@mastra/core/mastra";
import { PinoLogger } from "@mastra/loggers";
import { chat } from "./agents/chat";
import { storage } from "./storage";

export const mastra = new Mastra({
  workflows: { weatherWorkflow },
  agents: { chat, weather },
  storage,
  logger: new PinoLogger(),
  telemetry: { enabled: false },
  observability: {
    configs: {
      default: {
        serviceName: "mastra",
        sampling: { type: SamplingStrategyType.ALWAYS },
        processors: [],
        exporters: [defaultExporter],
      },
    },
  },
});
```

#### Storage Configuration (`src/mastra/storage.ts`)

- Tested it with local libSQL storage (see configuration below) and Postgres
- The `dbPath` joining is necessary so that Next.js and Mastra Studio write/read from the same directory `.mastra/output`.

```typescript
import { join } from "node:path";
import { LibSQLStore } from "@mastra/libsql";

const cwd = process.cwd();
const isPlayground = cwd.endsWith(".mastra/output");

const dbPath = isPlayground
  ? join(cwd, "mastra.db")
  : join(cwd, ".mastra", "output", "mastra.db");

export const storage = new LibSQLStore({
  url: `file:${dbPath}`,
});
```

## Expected Behavior

**Expected behavior:** Messages loaded from storage should match the exact content and order from the stream

**Actual behavior:** First text content is missing, and text/tool invocation order is incorrect

### Environment Information

```json
{
  "dependencies": {
    "@mastra/ai-sdk": "^0.2.6",
    "@mastra/core": "0.24.0",
    "@mastra/libsql": "^0.16.2",
    "@mastra/loggers": "^0.10.19",
    "@mastra/memory": "^0.15.11",
    "@ai-sdk/anthropic": "^2.0.37",
    "ai": "^5.0.80",
    "mastra": "^0.18.0",
    "next": "16.0.1",
    "react": "19.2.0"
  },
  "node": "v20+",
  "pnpm": "10.20.0"
}
```

## Verification

- [x] I have searched the existing issues to make sure this is not a duplicate
- [x] I have included sufficient information for the team to reproduce and understand the issue

### PR DESCRIPTION
**Pull request by abhiaiyer91**
## Description

Add integration tests to verify message part ordering is preserved through the stream → storage → recall cycle.

## What this PR does

Adds a new test file `packages/memory/integration-tests-v5/src/message-ordering.test.ts` that:

1. **Tracks stream order** - Records TEXT, TOOL, STEP chunks as they stream from the LLM
2. **Queries raw storage** - Direct `listMessages()` query to see what's in the database
3. **Queries recall** - `memory.recall()` output to see what Memory returns
4. **Compares all three** - Verifies they match and text ordering is preserved

## Tests included

- `should preserve text ordering: stream -> raw storage -> recall`
- `should preserve ordering with multiple tool calls`
- `should match stream order exactly in storage`

## Related Issue

Closes #9909 (adds regression tests)

## How to run

```bash
cd packages/memory/integration-tests-v5
pnpm test:ordering
```

Requires `OPENAI_API_KEY` environment variable.

## Summary by CodeRabbit

* **Tests**
  * Added new integration tests and test scripts to validate message-part ordering and streaming ID behavior across providers and storage/recall flows.

* **Bug Fixes**
  * Resolved duplicate streaming text ID issues for some providers by normalizing per-step IDs to preserve ordering and non-lossy storage/recall.

* **Chores**
  * Updated AI SDK test tooling and dev dependencies, including Anthropic and related SDK updates.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: packages/core/src/stream/aisdk/v5/input.ts [hunk 1]
```diff
@@ -19,11 +29,40 @@ export class AISDKV5InputStream extends MastraModelInput {
...
+            transformedChunk.type === 'text-delta' ||
+            transformedChunk.type === 'text-end') &&
+          transformedChunk.payload?.id &&
+          isNumericId(transformedChunk.payload.id)
+        ) {
+          const originalId = transformedChunk.payload.id;
+          if (!idMap.has(originalId)) {
+            idMap.set(originalId, randomUUID());
+          }
+          transformedChunk.payload.id = idMap.get(originalId)!;
```
Comment (DanielSLew) [inline packages/core/src/stream/aisdk/v5/input.ts:75]: Can't you pass in an id generator for ai sdk? Maybe we want to use that and fallback to `randomUUID()` if it's not set

**Review by DanielSLew — APPROVED** [review]

**Review by CalebBarnes — APPROVED** [review]
