### PR TITLE
Analyze tools exports even when unused

### LINKED ISSUE #5149: [BUG] Bundling Error: createQueryVectorTool fails the build if not used in an agent.
### Describe the Bug

When you have a tool in the tools directory that uses createQueryVectorTool, but that tool isn't used by an agent you get the following error:

```
error: {
      "binding": "ZodObject",
      "code": "MISSING_EXPORT",
      "exporter": ".mastra/.build/zod.mjs",
      "id": "/Users/abhiramaiyer/PlatformFirst/stream-test/node_modules/@mastra/schema-compat/dist/index.js",
      "url": "https://rollupjs.org/troubleshooting/#error-name-is-not-exported-by-module",
      "pos": 22,
      "loc": {
        "column": 22,
        "file": "/Users/abhiramaiyer/PlatformFirst/stream-test/node_modules/@mastra/schema-compat/dist/index.js",
        "line": 1
      },
      "frame": "1: import { ZodOptional, ZodObject, ZodArray, ZodUnion, ZodString, ZodNumber, z, ZodDefault, ZodDate } from 'zod';\n                         ^\n2: import { jsonSchema } from 'ai';\n3: import { convertJsonSchemaToZod } from 'zod-from-json-schema';",
```

### Steps To Reproduce

1. add a tool in the tools dir

```
import { openai } from '@ai-sdk/openai';
import { createVectorQueryTool } from '@mastra/rag';


export const vectorTool = createVectorQueryTool({
    indexName: 'vector-index',
    vectorStoreName: 'vector-store',
    model: openai.embedding('text-embedding-ada-002')
})
```

2. Run mastra build

### Expected Behavior

It shouldn't fail the build

### Environment Information

Latest all packages

### Verification

- [x] I have searched the existing issues to make sure this is not a duplicate
- [x] I have included sufficient information for the team to reproduce and understand the issue

### PR DESCRIPTION
**Pull request by wardpeet**
## Description

Analyze tools exports even when unused. This way we make sure we capture all exports

## Related Issue(s)

Fixes #5149

## Type of Change

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Code refactoring
- [ ] Performance improvement
- [ ] Test update

## Checklist

- [ ] I have made corresponding changes to the documentation (if applicable)
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: packages/deployer/src/build/analyze.ts [hunk 1]
```diff
@@ -369,15 +369,28 @@ async function validateOutput(
...
+      if (depsToOptimize.has(dep)) {
+        // Merge with existing exports if dependency already exists
+        const existingExports = depsToOptimize.get(dep)!;
+        depsToOptimize.set(dep, [...new Set([...existingExports, ...exports])]);
+      } else {
+        depsToOptimize.set(dep, exports);
+      }
+    }
+  }
+  console.log(depsToOptimize);
```
Comment (DanielSLew) [inline packages/deployer/src/build/analyze.ts]:
```suggestion
```

**Review by DanielSLew — APPROVED** [review]
