### PR TITLE
mastra build - fix indirect external deps installation

### LINKED ISSUE #8052: [BUG] The fastembed dependency is missing from the .mastra/output after running mastra build
### Describe the Bug

I have started exploring mastra and in my "hello-world" app I decided to play with the Semantic Recall and (following the docs) I configured the "@mastra/fastembed". Everything works in dev and the prod build succeeds with no errors. Running the prod build also works, but if I delete the root node_modules (as I should in prod deployment, because .mastra/ already contains the dependencies) then I get:

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'fastembed' imported from /Users/..../mastra-fastembed-repro/.mastra/output/index.mjs

### Steps To Reproduce

I have created a minimal repro repository -> https://github.com/flashd2n/mastra-fastembed-build-missing-repro

### Expected Behavior

The prod build directory should contain everything necessary for deployment. 

### Environment Information

- OS: macOS Sequoia 15.6.1
- CPU: Apple M1 Pro
- Memory: 16 GB
- Node.js: v20.19.4
- npm: 10.8.2
- mastra: 0.13.1

### Verification

- [x] I have searched the existing issues to make sure this is not a duplicate
- [x] I have included sufficient information for the team to reproduce and understand the issue

### PR DESCRIPTION
**Pull request by TheIsrael1**
- **Mastra build - Fix indirect external deps installation**
- **changeset**

## Related Issue(s)
Fixes #8052

## Type of Change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Code refactoring
- [ ] Performance improvement
- [ ] Test update

## Checklist

- [ ] I have made corresponding changes to the documentation (if applicable)
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: packages/deployer/src/bundler/index.ts [hunk 1]
```diff
@@ -365,7 +365,7 @@ export abstract class Bundler extends MastraBundler {
         const rootPath = await getPackageRootPath(dep);
         const pkg = await readJSON(`${rootPath}/package.json`);
 
-        dependenciesToInstall.set(dep, pkg.version);
+        dependenciesToInstall.set(dep, pkg.version || 'latest');
```
Comment (wardpeet) [inline packages/deployer/src/bundler/index.ts:368]:
```suggestion
        // TODO figure out why this is necessary? Why can't we resolve the pkg.version
        dependenciesToInstall.set(dep, pkg.version || 'latest');
```

**Review by wardpeet — APPROVED** [review]
There is probably a different issue here but happy to merge it after you add a todo :)
