### PR TITLE
fix: resolve TypeScript path aliases in transpiled workspace packages

### LINKED ISSUE #11790: Monorepo Issue on dev
This issue was created from Discord post 1459811343501627402:

[Open in Discord](https://discord.com/channels/1309558646228779139/1459811343501627402)

I am using Mastra in a turborepo setup, so my main mastra depends on @repo/database which does not work on dev instance with path alias, `@db` or directory imports.

### PR DESCRIPTION
**Pull request by TheIsrael1**
## Description

Fixes #11790

This PR resolves an issue where TypeScript path aliases (e.g., `@/*` → `./src/*`) in workspace packages configured with `transpilePackages` were not being resolved during the bundling process, causing build failures in monorepo setups.

## Problem

When using Mastra in a monorepo with:
- Workspace packages containing TypeScript path aliases
- These packages listed in `bundler.transpilePackages`

The bundler would fail to resolve imports using those path aliases, resulting in errors like:
```
ERROR: We couldn't load "@/nested" from "@repo/internal"
```

## Root Cause

The `tsConfigPaths` plugin was only present in the `analyzeEntry` phase but was missing from the `bundleExternals` phase where transpiled workspace packages are processed.

## Solution

- Added `tsConfigPaths()` plugin to the `bundleExternals` phase in `packages/deployer/src/build/analyze/bundleExternals.ts`
- Configured the plugin with `order: 'pre'` to ensure it runs before other resolvers

## Changes

**Core Fix:**
- `packages/deployer/src/build/analyze/bundleExternals.ts` - Add tsConfigPaths plugin to bundleExternals phase
- `packages/deployer/src/build/plugins/tsconfig-paths.ts` - Add `order: 'pre'` for proper resolution priority

**E2E Test Coverage:**
- Added test fixture with path aliases in workspace package (`e2e-tests/monorepo/template/packages/inner-tools/`)
- Added test assertion to verify path aliases are resolved in bundled output
- Test: `e2e-tests/monorepo/monorepo.test.ts` - "should resolve workspace package tsconfig paths"

## Testing

✅ All unit tests pass (32/32)
✅ E2E tests verify path aliases work in both main app and workspace packages (8/11 passing, 3 skipped due to unrelated dev mode issue)

Tested with reproduction case from issue #11790 - build now succeeds where it previously failed.

## Summary by CodeRabbit

* **Bug Fixes**
  * Fixed TypeScript path alias resolution in monorepo workspace packages. Path aliases are now properly resolved during bundling, preventing build failures in transpiled workspace package setups.

* **Tests**
  * Added test coverage validating that path aliases are correctly resolved in bundled output.

### CODE REVIEW

File: e2e-tests/monorepo/template/apps/custom/src/mastra/index.ts [hunk 1]
```diff
@@ -14,6 +14,7 @@ export const mastra = new Mastra({
   },
   bundler: {
     externals: ['bcrypt'],
+    transpilePackages: ['@inner/inner-tools'],
```
Comment (wardpeet) [inline e2e-tests/monorepo/template/apps/custom/src/mastra/index.ts]: I don't think this is necessary

File: e2e-tests/monorepo/template/packages/inner-tools/src/index.ts [hunk 2]
```diff
@@ -1,7 +1,7 @@
 import { createTool } from '@mastra/core/tools';
-import bcrypt from 'bcrypt';
```
Comment (wardpeet) [inline e2e-tests/monorepo/template/packages/inner-tools/src/index.ts:2]: we need to keep this for other checks

File: e2e-tests/monorepo/template/packages/inner-tools/package.json [hunk 3]
```diff
@@ -13,7 +13,6 @@
   "dependencies": {
     "@mastra/core": "monorepo-test",
     "@inner/lodash": "workspace:*",
-    "bcrypt": "^6.0.0",
```
Comment (wardpeet) [inline e2e-tests/monorepo/template/packages/inner-tools/package.json:16]: keep this

File: e2e-tests/monorepo/template/packages/inner-tools/src/index.ts [hunk 4]
```diff
@@ -2,6 +2,7 @@ import { createTool } from '@mastra/core/tools';
 import bcrypt from 'bcrypt';
```
Comment (wardpeet) [inline e2e-tests/monorepo/template/packages/inner-tools/src/index.ts:2]:
```suggestion
```

File: e2e-tests/monorepo/template/packages/inner-tools/src/utils/password-utils.ts [hunk 5]
```diff
@@ -0,0 +1,8 @@
+export async function hashPassword(password: string): Promise<string> {
+  // Simple hash function for testing (not for production use)
+  return `hashed_${password}`;
+}
```
Comment (wardpeet) [inline e2e-tests/monorepo/template/packages/inner-tools/src/utils/password-utils.ts]:
```suggestion
import bcrypt from 'bcrypt';

export function hashPassword(password: string): Promise<string> {
  // Simple hash function for testing (not for production use)
  return bcrypt.hash(`hashed_${password}`);
}
```

**Review by wardpeet — APPROVED** [review]
