### PR TITLE
Client JS - Fix agent streamVNext clientTool calls

### LINKED ISSUE #7426: [BUG] `clientTools` do not seem to execute when using Agent#streamVNext with client-js sdk
### Describe the Bug

`clientTools` are not being executed when using `agent.streamVNext` with the client sdk.
The stream ends with the following reasong:
```ts
    stepResult: { reason: 'tool-calls', isContinued: false },
```

### Steps To Reproduce

Invoke an agent with the following client script:

```ts
import { MastraClient } from "@mastra/client-js";
import { createTool } from "@mastra/core/tools";
import z from "zod";

const logTool = createTool({
    id: "log",
    description: "Logs a message to the client console",
    inputSchema: z.object({
        message: z.string().describe("The message to log"),
    }),
    outputSchema: z.object({
        status: z.enum(["logged"]),
        message: z.string(),
    }),
    execute: async ({ context: { message } }) => {
        console.log("[log tool] message:", message);
        return { status: "logged", message };
    }
})

const BASE_URL = "http://localhost:4111";

async function main() {
  const client = new MastraClient({ baseUrl: BASE_URL });

  const agentId = "sample-agent";
  const agent = client.getAgent(agentId);

  console.log("Calling agent.streamVNext with clientTools...");

  const response = await agent.streamVNext({
    messages: [{ role: "user", content: "Please invoke the log tool" }],
    clientTools: { log: logTool },
  });

  if (!response.body) {
    console.error("No response body from streamVNext");
    return;
  }

  await response.processDataStream({
    onChunk: async (chunk) => {
      switch (chunk.type) {
        case "text-delta":
          process.stdout.write(chunk.payload.text);
          break;
        case "tool-call":
          console.log("\n[client] tool-call chunk:", chunk.payload);
          const { toolName, args } = chunk.payload;
          console.log(`[client] Invoking tool ${toolName} with args:`, args);
          break;
        case "tool-result":
          console.log("\n[client] server tool-result:", chunk.payload);
          break;
        default:
          console.log("[client] chunk:", chunk);
      }
    },
  });

  console.log("\nclient finished");
}

main().catch((err) => {
  console.error("client error:", err);
});
```

### Expected Behavior

Execute the `clientTools` and not end the stream

### Environment Information

    "@mastra/core": "0.15.3"

### Verification

- [x] I have searched the existing issues to make sure this is not a duplicate
- [x] I have included sufficient information for the team to reproduce and understand the issue

### PR DESCRIPTION
**Pull request by TheIsrael1**
## Description
Fix clientTools execution in the client SDK with agent streamVNext

## Related Issue(s)

Fixes #7426

## Type of Change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Code refactoring
- [ ] Performance improvement
- [ ] Test update

## Checklist

- [ ] I have made corresponding changes to the documentation (if applicable)
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: client-sdks/client-js/src/resources/agent.ts [hunk 1]
```diff
@@ -1195,33 +1218,19 @@ export class Agent extends BaseResource {
                   toolInvocation.result = result;
                 }
 
-                // write the tool result part to the stream
-                const writer = writable.getWriter();
-
```
Comment (TheIsrael1) [inline client-sdks/client-js/src/resources/agent.ts:1200]: The core stream now adds the tool-result so we don't need to add it here

**Review by wardpeet — APPROVED** [review]
