### PR TITLE
fix(deployer): Transitive deps fixes

### LINKED ISSUE #8218: [DISCORD:1420847587052752896] turborepo local package dependencies cascading?
This issue was created from Discord post: https://discord.com/channels/1309558646228779139/1420847587052752896

after upgrading some mastra packages I now started getting this error:
```
◐ Preparing development environment...
✓ Initial bundle complete
◇ Starting Mastra dev server...

node:internal/modules/run_main:122
    triggerUncaughtException(
    ^
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@aws-sdk/client-s3' imported from /Users/amosbastian/Development/reel/packages/worker-core/node_modules/.cache/@autovirality-worker-core-workflow.mjs
```

basically my main ap has `worker-core` a  dependency, which is a local package, and it that package has a depdency to another local package `cloudflare` that has `@aws-sdk/client-s3` as a dependency... not sure what is going on here all of a sudden. I build everything with tsc

### PR DESCRIPTION
**Pull request by LekoArts**
## Description

- Fix Rollup chunk placement in dev mode for monorepo workspace packages by writing shared chunks to package-specific cache directories instead of the global
output folder
- Add validation to detect and reject invalid cross-package chunks with helpful error message

Changes:

- Convert chunkFileNames from static string to function that inspects chunk module origins
- Route workspace package chunks to <pkg>/node_modules/.cache during dev mode
- Throw error when a chunk spans multiple workspace packages (edge case requiring investigation)
- Fall back to default .mastra/output path for external dependencies

## Related Issue(s)

Fixes https://github.com/mastra-ai/mastra/issues/8218

## Type of Change

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Code refactoring
- [ ] Performance improvement
- [ ] Test update

## Checklist

- [ ] I have made corresponding changes to the documentation (if applicable)
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: packages/deployer/src/build/analyze/bundleExternals.ts [hunk 1]
```diff
@@ -299,7 +299,47 @@ async function buildExternalDependencies(
...
+      /**
+       * This whole bunch of logic directly below is for the edge case shown in the e2e-tests/monorepo with "tinyrainbow" package. It's used in multiple places in the package and as such Rollup creates a shared chunk for it. During 'mastra dev', we don't want that chunk to show up in the '.mastra/output' folder (outputDirRelative) but inside <pkg>/node_modules/.cache instead.
+       * We only care about this during 'mastra dev'!
+       */
+      if (bundlerOptions.isDev) {
+        const importedFromPackages = new Set<string>();
+
+        for (const moduleId of chunkInfo.moduleIds) {
+          const normalized = slash(moduleId);
+          for (const [pkgName, pkgInfo] of workspaceMap.entries()) {
```
Comment (wardpeet) [inline packages/deployer/src/build/analyze/bundleExternals.ts:312]: Did you find any places where it wasn't in the workspace?

**Review by wardpeet — APPROVED** [review]

File: packages/deployer/src/build/analyze/bundleExternals.ts (hunk 1 above)
Comment (LekoArts) [reply packages/deployer/src/build/analyze/bundleExternals.ts:312]: No, I couldn’t force that but better safe than sorry to account for that. Let’s see if people open issues
