### PR TITLE
fix(cli): Get init working again

### LINKED ISSUE #7729: [BUG] Error running the init function
### Describe the Bug

I just tried running the [one-liner command](https://mastra.ai/en/docs/frameworks/web-frameworks/next-js#1-use-the-one-liner) to set up Mastra with NextJS and am getting dependency conflict error with Zod. 

Image

### Steps To Reproduce

just run either the [one-liner](https://mastra.ai/en/docs/frameworks/web-frameworks/next-js#1-use-the-one-liner) or just the init command below in your terminal and select `y` for "OK to proceed?"

`npx mastra@latest init`

### Expected Behavior

_No response_

### Environment Information

- Node.js version 22.14.0
- npm version 11.6.0

### Verification

- [x] I have searched the existing issues to make sure this is not a duplicate
- [x] I have included sufficient information for the team to reproduce and understand the issue

### PR DESCRIPTION
**Pull request by LekoArts**
## Description

The `mastra init` CLI had two problems:

- Import from `@mastra/core` which is a peer-dep and not installed during `npx` run
  - Error then: `Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@mastra/core' imported from /Users/lejoe/.npm/_npx/6d834dabfb7dcda4/node_modules/mastra/dist/index.js`
- Asked for confirmation to install core deps that we know are required. Just install them without asking

## Related Issue(s)

Fixes #7729

## Type of Change

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Code refactoring
- [ ] Performance improvement
- [ ] Test update

## Checklist

- [ ] I have made corresponding changes to the documentation (if applicable)
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: packages/cli/src/commands/build/build.ts [hunk 1]
```diff
@@ -64,11 +63,18 @@ export async function build({
     });
     logger.info('You can now deploy the .mastra/output directory to your target platform.');
   } catch (error) {
-    if (error instanceof MastraError) {
-      const { message, ...details } = error.toJSONDetails();
-      logger.error(`${message}`, details);
-    } else if (error instanceof Error) {
-      logger.error(`Mastra Build failed`, { error });
+    try {
+      const { MastraError } = await import('@mastra/core/error');
```
Comment (wardpeet) [inline packages/cli/src/commands/build/build.ts:67]: Why the dynamic import?

**Review by wardpeet — APPROVED** [review]

File: packages/cli/src/commands/build/build.ts (hunk 1 above)
Comment (LekoArts) [reply packages/cli/src/commands/build/build.ts:67]: Because of the first error:

- Import from `@mastra/core` which is a peer-dep and not installed during `npx` run
  - Error then: `Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@mastra/core' imported from /Users/lejoe/.npm/_npx/6d834dabfb7dcda4/node_modules/mastra/dist/index.js`

When you run `npx mastra@latest init` you're running the bundled `dist/index.js` file that contains the import. core is a peerdep and not installed during `npx` so it errors on that
