### PR TITLE
Fix: Show "No Input" for empty workflow steps (#2696)

### LINKED ISSUE #2696: Mastra dev UI shows "not serializable" when there are no inputs to workflow steps
Hey team - when running workflows and debugging in the Mastra dev UI, steps invoked without inputs show the input as "Not Serializable". Ideally we could show "no input"?

Image

### PR DESCRIPTION
**Pull request by OmkarBansod02**
### Changes:  
-  **Reverted Telemetry Changes**: Restored original telemetry behavior.
- **UI Fix in `trace-span-details.tsx`**:  
  - Updated the `AttributesValues` component to display `"No Input"` for:  
    - `null` values  
    - `undefined` values  
    - Empty arrays `[]`  
    - Empty objects `{}`  
- **UI Clarity**: Improved user experience by consistently displaying `"No Input"` for empty attributes, maintaining clarity when debugging workflows with steps that have no inputs.

### CODE REVIEW

**Comment by wardpeet** [comment]
@OmkarBansod02 why should we show no inputs? Instead of not adding any attributes?

File: packages/core/src/telemetry/telemetry.ts [hunk 1]
```diff
@@ -177,13 +177,17 @@ export class Telemetry {
...
 
         // Record input arguments as span attributes
-        args.forEach((arg, index) => {
-          try {
-            span.setAttribute(`${context.spanName}.argument.${index}`, JSON.stringify(arg));
-          } catch {
-            span.setAttribute(`${context.spanName}.argument.${index}`, '[Not Serializable]');
-          }
-        });
+        if (args.length === 0) {
```
Comment (wardpeet) [inline packages/core/src/telemetry/telemetry.ts]: Let's fix this in the playground UI instead. I'm not sure why we're showing Not Serializable. What we can do is first filter all args  if they are undefined but not sure if, it's necessary

Comment (OmkarBansod02) [reply packages/core/src/telemetry/telemetry.ts]: I initially considered checking each argument individually to handle `null` or `undefined`  values:
 
```typescript 
args.forEach((arg, index) => {
  if (arg === undefined || arg === null) {
    span.setAttribute(`${context.spanName}.argument.${index}`, 'No Input');
  }
```
I opted for the current telemetry fix to ensure consistent and accurate data at the source.

As for the fix in the Playground UI, I believe we would need to make changes in multiple files. not sure about it but I'd love to explore it further.

Comment (wardpeet) [reply packages/core/src/telemetry/telemetry.ts]: I'm not sure why we should even set an argument if it's null or undefined

**Review by wardpeet — APPROVED** [review]
You're a beast! 🐻 Thank you for pivoting and driving this home!
