### PR TITLE
fix(@mastra/core, @mastra/memory, @mastra/pg): semantic recall perf + memory bundle size

### LINKED ISSUE #3236: [BUG] Custom vector database and embedder in memory semantic search cause Error saving response
### Describe the Bug
Using embedder `nomic-embed-text` and pgVector, semanticRecall will report error:

```
    error: {
      "length": 93,
      "name": "error",
      "severity": "ERROR",
      "code": "22000",
      "file": "vector.c",
      "line": "72",
      "routine": "CheckExpectedDim"
    }
```

### Steps To Reproduce

1. use the code above

### Expected Behavior

no error, store vector success.

### Environment Information

```
    "@mastra/core": "^0.6.3",
    "@mastra/loggers": "^0.1.12",
    "@mastra/memory": "^0.2.4",
    "@mastra/pg": "^0.2.4",
    "@mastra/rag": "^0.1.12",
    "ai": "^4.2.0",
    "mastra": "^0.4.2",
    "ollama-ai-provider": "^1.2.0",
```

### Component

Memory

### Code Snippet

```typescript
async function vectorTest() {
  const memory = new Memory({
    storage: new PostgresStore({
      connectionString: process.env.POSTGRES_CONNECTION_STRING!,
    }),

    options: {
      // semanticRecall: false,
      semanticRecall: {
        topK: 10, // Include 10 most relevant past messages
        messageRange: 2, // Messages before and after each result
      },
      lastMessages: 5,
    },
    vector: new PgVector(process.env.POSTGRES_CONNECTION_STRING!),

    embedder: ollama.embedding("nomic-embed-text"),
  });

  const agent = new Agent({
    name: "Project Manager",
    instructions: "say something",
    model: openai("gpt-4o-mini"),
    memory: memory,
  });
  await agent.generate(`hello`, { threadId: "v_test_1", resourceId: "v-1" });
  await agent.generate(`hello, twice`, {
    threadId: "v_test_1",
    resourceId: "v-1",
  });
  await agent.generate(`hello, 3`, { threadId: "v_test_1", resourceId: "v-1" });
  await agent.generate(`hello, 4`, { threadId: "v_test_1", resourceId: "v-1" });
  const rs3 = await agent.generate(`hello`, {
    threadId: "v_test_1",
    resourceId: "v-1",
  });
  console.log("rs3", rs3);
}
```

### Error Logs

```shell
ERROR [2025-03-25 10:45:18.564 +0800] (AGENT - undefined): Error saving response
    runId: "4a99487a-c2f2-4121-a9a3-e6be914c35d4"
    result: {
      "text": "Hello there! How can I help you today?\n",
      "toolResults": [],
      "toolCalls": [],
      "usage": {
        "promptTokens": 5,
        "completionTokens": 11,
        "totalTokens": 16
      },
      "steps": [
        {
          "stepType": "initial",
          "text": "Hello there! How can I help you today?\n",
          "toolResults": [],
          "toolCalls": [],
          "usage": {
            "promptTokens": 5,
            "completionTokens": 11,
            "totalTokens": 16
          }
        }
      ]
    }
    threadId: "v_test_1"
    error: {
      "length": 93,
      "name": "error",
      "severity": "ERROR",
      "code": "22000",
      "file": "vector.c",
      "line": "72",
      "routine": "CheckExpectedDim"
    }
```

### Additional Context

_No response_

### Verification

- [x] I have searched the existing issues to make sure this is not a duplicate
- [x] I have included sufficient information for the team to reproduce and understand the issue

### PR DESCRIPTION
**Pull request by TylerBarnes**
## Semantic recall perf + memory bundle size
Before this it would take around 2.5 to 3 seconds before we sent a req to the LLM while we were processing semantic recall (embedding messages, querying db, etc). After this change it takes between 800ms and 1.1s. This is when using pgvector. This should also have a perf improvement for other vector stores but probably not as big of a change.

Changes:
1. removed `@mastra/rag` from `@mastra/memory`, now it uses `tiktoken-js` to do chunking (this should also fix the bundle size issue https://github.com/mastra-ai/mastra/issues/3309 )
2. uses measured dimensions instead of hardcoded dimensions and parallelizes embeddings as much as possible (most likely fixes https://github.com/mastra-ai/mastra/issues/3236 )
3. combines 2 memory.saveMessages calls into one
4. combined another 2 memory.getThreadById() calls into one
5. adds a chunk/embedding in memory cache for Memory
6. swapped out pg vector advisory locks for in memory mutexes (saves almost a second of time on each request)
7. combined multiple pg queries into single queries, removed extra checks for if a table/index exists before the query to create it (since the query that creates them uses `IF NOT EXISTS` anyway)
8. adds an in memory (on the class instance) cache for creating indexes in pg and for getting index info, saves around 700ms per request

Semantic recall is between 2 to 3 times faster with these changes

### CODE REVIEW

File: stores/pg/src/vector/index.ts [hunk 1]
```diff
@@ -205,13 +229,23 @@ export class PgVector extends MastraVector {
...
     try {
       // Validate inputs
       if (!indexName.match(/^[a-zA-Z_][a-zA-Z0-9_]*$/)) {
+        this.createdIndexes.delete(indexName);
         throw new Error('Invalid index name format');
       }
       if (!Number.isInteger(dimension) || dimension <= 0) {
+        this.createdIndexes.delete(indexName);
         throw new Error('Dimension must be a positive integer');
       }
```
Comment (NikAiyer) [inline stores/pg/src/vector/index.ts]: What happens if we set the index in the map after these two checks? Or even after setupIndex is done?

**Review by NikAiyer — APPROVED** [review]
LGTM!
