### PR TITLE
Fix vercel deployer mastra deploy, load env vars

### LINKED ISSUE #3009: [BUG] Vercel Deployer Not Including Env Variables
### Describe the Bug

When using the VercelDeployer and running the command `npx mastra deploy vercel` the project is created and deployed on Vercel, but the command attempts to sync environment variables then throws this error:

```Failed to sync environment variables: Could not find project ID. Make sure the project has been deployed first.```

When I try to update the .env file in the Vercel dashboard I get this error:
```The `projectSettings` object is required for new projects, but is missing in the deployment payload```

### Steps To Reproduce

1. `npx create-mastra@latest`
2.  Add the following code to the base `index.ts` file in the `Mastra` object: ```deployer: new VercelDeployer({
    teamId: "my-team-id",
    projectName: "mastra",
    token: "my-token",
  }),```
3. Run `npx mastra deploy vercel`

### Expected Behavior

Deployment to Vercel include .env variables and allows for editing in the Vercel dashboard.

### Environment Information

- Mastra: 0.6.0
- Mastra Vercel Deployer: 0.1.9
- MacOS
- OpenAI
- Chrome 134

### Component

CLI

### Code Snippet

```typescript
export const mastra = new Mastra({
  workflows: { weatherWorkflow },
  agents: { weatherAgent },
  logger: createLogger({
    name: "Mastra",
    level: "info",
  }),
  deployer: new VercelDeployer({
    teamId: "teamid",
    projectName: "mastra",
    token: "token",
  }),
});
```

### Error Logs

```shell
INFO [2025-03-17 15:53:59.962 -0700] (DEPLOYER - VERCEL): Deployment started on Vercel. You can wait for it to finish or exit this command.
Syncing environment variables...
Failed to sync environment variables: Could not find project ID. Make sure the project has been deployed first.
```

### Additional Context

_No response_

### Verification

- [x] I have searched the existing issues to make sure this is not a duplicate
- [x] I have included sufficient information for the team to reproduce and understand the issue

### PR DESCRIPTION
**Pull request by TheIsrael1**
Fixes #3009

### CODE REVIEW

**Review by wardpeet — APPROVED** [review]
Which one is easiest to find the team id or the team slug? Cause maybe we should just ask for the team slug

File: packages/deployer/src/build/bundler.ts [hunk 1]
```diff
@@ -53,6 +54,9 @@ export async function getInputOptions(
     external: externals,
     plugins: [
       tsConfigPaths(),
+      dotenv({
```
Comment (wardpeet) [inline packages/deployer/src/build/bundler.ts]: Just add this to build command, not in the bundler ;)

**Comment by TheIsrael1** [comment]
> Which one is easiest to find the team id or the team slug? Cause maybe we should just ask for the team slug

Definitely easier to ask for teamSlug, updates made!

File: packages/deployer/src/build/bundler.ts (hunk 1 above)
Comment (TheIsrael1) [reply packages/deployer/src/build/bundler.ts]: looks like we don't need dot env here, just in the deployer bundler, for when people do mastra deploy

for the build story, you'll build output and and deploy yourself, you you'll control how you pass the vars

File: packages/deployer/package.json [hunk 2]
```diff
@@ -99,6 +99,7 @@
     "hono": "^4.7.4",
     "resolve-from": "^5.0.0",
     "rollup": "^4.35.0",
+    "rollup-plugin-dotenv": "^0.5.1",
```
Comment (wardpeet) [inline packages/deployer/package.json]:
```suggestion
```

File: packages/deployer/src/build/deployer.ts [hunk 3]
```diff
@@ -57,6 +58,9 @@ export function getDeployerBundler(entryFile: string) {
           });
         },
       },
+      dotenv({
+        envKey: 'production',
+      }),
```
Comment (wardpeet) [inline packages/deployer/src/build/deployer.ts]:
```suggestion,
```

File: packages/deployer/src/build/deployer.ts [hunk 4]
```diff
@@ -2,6 +2,7 @@ import * as babel from '@babel/core';
 import type { MastraDeployer } from '@mastra/core';
 import { rollup } from 'rollup';
 import esbuild from 'rollup-plugin-esbuild';
+import dotenv from 'rollup-plugin-dotenv';
```
Comment (wardpeet) [inline packages/deployer/src/build/deployer.ts]:
```suggestion
```

**Review by wardpeet — APPROVED** [review]
