### PR TITLE
fix/11760  claude 4.5 params

### LINKED ISSUE #11760: [BUG] Issue running anthropic models in the studio/playground
### Describe the Bug

When I try to use `'anthropic/claude-haiku-4-5'` model in the playground, I get this error:

```
{"message":"`temperature` and `top_p` cannot both be specified for this model. Please use only one.","name":"AI_APICallError","stack":"AI_APICallError: `temperature` and `top_p` cannot both be specified for this model. Please use only one.\n at file:///Users/epinzur/src/github.com/mastra-ai/mastra/packages/core/dist/chunk-YWUDQUAV.js:1073:14\n at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n at async postToApi (file:///Users/epinzur/src/github.com/mastra-ai/mastra/packages/core/dist/chunk-YWUDQUAV.js:937:28)\n at async AnthropicMessagesLanguageModel.doStream (file:///Users/epinzur/src/github.com/mastra-ai/mastra/packages/core/dist/chunk-YWUDQUAV.js:5870:50)\n at async AISDKV5LanguageModel.doStream (file:///Users/epinzur/src/github.com/mastra-ai/mastra/packages/core/dist/chunk-JRF5JQCH.js:914:12)\n at async pRetry.default.retries (file:///Users/epinzur/src/github.com/mastra-ai/mastra/packages/core/dist/chunk-UWFDMMNO.js:10412:34)\n at async Module.pRetry (file:///Users/epinzur/src/github.com/mastra-ai/mastra/node_modules/.pnpm/p-retry@7.1.0/node_modules/p-retry/index.js:195:19)\n at async createStream (file:///Users/epinzur/src/github.com/mastra-ai/mastra/packages/core/dist/chunk-UWFDMMNO.js:10409:16)\n at async Object.start (file:///Users/epinzur/src/github.com/mastra-ai/mastra/packages/core/dist/chunk-UWFDMMNO.js:10275:27)","url":"https://api.anthropic.com/v1/messages","requestBodyValues":{"model":"claude-haiku-4-5","max_tokens":64000,"temperature":0.5,"top_p":1,"system":[{"type":"text","text":"please generate a name for a spaceship"}],"messages":[{"role":"user","content":[{"type":"text","text":"do it"}]}],"stream":true},"statusCode":400,"responseHeaders":{"anthropic-organization-id":"39cad08d-cc0f-45d3-847f-553c5c75d35a","cf-cache-status":"DYNAMIC","cf-ray":"9bb4b4477ff615ec-TXL","connection":"keep-alive","content-length":"201","content-type":"application/json","date":"Fri, 09 Jan 2026 14:42:57 GMT","request-id":"req_011CWwyrhZmb8K5sd9FtooXD","server":"cloudflare","strict-transport-security":"max-age=31536000; includeSubDomains; preload","x-envoy-upstream-service-time":"40","x-robots-tag":"none","x-should-retry":"false"},"responseBody":"{\"type\":\"error\",\"error\":{\"type\":\"invalid_request_error\",\"message\":\"`temperature` and `top_p` cannot both be specified for this model. Please use only one.\"},\"request_id\":\"req_011CWwyrhZmb8K5sd9FtooXD\"}","isRetryable":false,"data":{"type":"error","error":{"type":"invalid_request_error","message":"`temperature` and `top_p` cannot both be specified for this model. Please use only one."}}}
```

Seems like both of these params are now always passed when calling an agent in the studio UI.

### Steps To Reproduce

```
import { Agent } from '@mastra/core/agent';
import { Mastra } from '@mastra/core/mastra';

const astroForge = new Agent({
  id: 'astro-forge',
  name: 'Astro Forge',
  instructions: 'please generate a name for a spaceship',
  model: 'anthropic/claude-haiku-4-5',
})

export const mastra = new Mastra({
  agents: { astroForge },
});
```

Use this code in a mastra setup off the `main` branch.  In the UI try to run the agent. Boom, error!

### Link to Minimal Reproducible Example

nope

### Expected Behavior

Should execute the agent without issue.

### Environment Information

```block
System:
    OS: macOS 15.5
    CPU: (10) arm64 Apple M4
    Memory: 318.64 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 23.11.0 - /Users/epinzur/.nvm/versions/node/v23.11.0/bin/node
    npm: 10.9.2 - /Users/epinzur/.nvm/versions/node/v23.11.0/bin/npm
    pnpm: 10.18.2 - /Users/epinzur/.nvm/versions/node/v23.11.0/bin/pnpm
  Browsers:
    Chrome: 143.0.7499.193
    Safari: 18.5
  npmPackages:
    @mastra/arize: latest => 1.0.0-beta.11 
    @mastra/braintrust: latest => 1.0.0-beta.11 
    @mastra/core: latest => 1.0.0-beta.20 
    @mastra/langfuse: latest => 1.0.0-beta.10 
    @mastra/langsmith: latest => 1.0.0-beta.11 
    @mastra/libsql: latest => 1.0.0-beta.11 
    @mastra/observability: latest => 1.0.0-beta.10 
    @mastra/posthog: latest => 1.0.0-beta.10 
    @types/node: ^22.10.0 => 22.19.1 
    typescript: ^5.7.2 => 5.9.3 
    zod: ^3.25.76 => 3.25.76 
  npmGlobalPackages:
    corepack: 0.32.0
    eslint: 9.32.0
    hoodiecrow-imap: 2.1.0
    npm: 10.9.2
```

### Verification

- [x] I have searched the existing issues to make sure this is not a duplicate
- [x] I have included sufficient information for the team to reproduce and understand the issue

### PR DESCRIPTION
**Pull request by graysonhicks**
## Description

Fixes an issue where Anthropic Claude 4.5+ models fail in the studio/playground with the error: "`temperature` and `top_p` cannot both be specified for this model."

**Changes:**
- Add detection for Claude 4.5+ models that have this API restriction (using regex pattern matching on model IDs)
- Auto-clear `topP` when Claude 4.5+ models are detected and both values are set
- Show a warning banner when user manually sets both values for restricted models, allowing them to clear one
- Non-restricted models (OpenAI, Google, Claude 3.5, etc.) keep both defaults (`temperature: 0.5`, `topP: 1`)

**Known limitations:**
- Model detection relies on regex pattern matching against model IDs (e.g., `claude-*-4-5`), which may need updates as Anthropic releases new models

image

## Related Issue(s)

Fixes #11760

## Type of Change

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Code refactoring
- [ ] Performance improvement
- [x] Test update

## Checklist

- [x] I have made corresponding changes to the documentation (if applicable)
- [x] I have added tests that prove my fix is effective or that my feature works

## Summary by CodeRabbit

* **New Features**
  * Intelligent handling of Temperature and Top P for Claude 4.5+ models.
  * Automatically clears Top P when both parameters are set for restricted models.
  * Displays an in-app warning when users manually configure conflicting parameters.
  * Other providers (OpenAI, Google, Claude 3.5 and older) keep existing behavior.

* **Tests**
  * Added comprehensive tests covering model-specific parameter restrictions.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: packages/playground-ui/src/domains/agents/components/agent-settings.tsx [hunk 1]
```diff
@@ -66,6 +95,24 @@ export const AgentSettings = ({ agentId }: AgentSettingsProps) => {
...
+      hasSamplingRestriction &&
+      settings?.modelSettings?.temperature !== undefined &&
+      settings?.modelSettings?.topP !== undefined
+    ) {
+      setSettings({
+        ...settings,
+        modelSettings: { ...settings.modelSettings, topP: undefined },
+      });
+    }
+  }, [hasSamplingRestriction, agent?.provider, agent?.modelId]);
```
[the remark this answers is not in the document]
Comment (graysonhicks) [reply packages/playground-ui/src/domains/agents/components/agent-settings.tsx]: fixed

File: packages/playground-ui/src/domains/agents/hooks/__tests__/use-agent-settings-state.test.ts [hunk 2]
```diff
@@ -0,0 +1,100 @@
...
+
+  // Check for version 4.5+ patterns specifically
+  // Must match version 4.5 or higher (4-5, 4.5, 5-0, 5.0, etc.)
+  // But NOT match 3-5 or 3.5 (Claude 3.5 Sonnet, etc.)
+  const is45OrNewer =
+    /[^0-9]4[.-]5/.test(lowerModelId) || // Matches 4-5 or 4.5 but not 34-5
+    /[^0-9][5-9][.-]\d/.test(lowerModelId); // Matches 5-0, 6-0, etc. for future versions
+
+  return is45OrNewer;
+}
```
[the remark this answers is not in the document]
Comment (graysonhicks) [reply packages/playground-ui/src/domains/agents/hooks/__tests__/use-agent-settings-state.test.ts]: fixed

File: packages/playground-ui/src/domains/agents/components/agent-settings.tsx [hunk 3]
```diff
@@ -66,6 +68,33 @@ export const AgentSettings = ({ agentId }: AgentSettingsProps) => {
   const { data: memory, isLoading: isMemoryLoading } = useMemory(agentId);
   const { settings, setSettings, resetAll } = useAgentSettings();
 
+  // Check if this model has the temperature/topP mutual exclusion restriction
+  const hasSamplingRestriction = isAnthropicModelWithSamplingRestriction(agent?.provider, agent?.modelId);
```
Comment (mfrachet) [inline packages/playground-ui/src/domains/agents/components/agent-settings.tsx]: Can you make the entire logic a custom hook to avoid component pollution and behaviour isolation please?

File: packages/playground-ui/src/domains/agents/components/agent-settings.tsx [hunk 4]
```diff
@@ -66,6 +68,33 @@ export const AgentSettings = ({ agentId }: AgentSettingsProps) => {
...
+    if (!hasSamplingRestriction) {
+      clearedTopPRef.current = null;
+      return;
+    }
+
+    // Only clear topP once per agent/model combination when topP is defined
+    if (settings?.modelSettings?.topP !== undefined && clearedTopPRef.current !== agentModelKey) {
+      clearedTopPRef.current = agentModelKey;
+      setSettings({
+        ...settings,
```
Comment (mfrachet) [inline packages/playground-ui/src/domains/agents/components/agent-settings.tsx]: I think we can get rid of the useRef that creates a bunch of noise and makes things a bit harder to reason about. I've not tried it, but I think the following might fix your issue without the need of useRef:

```tsx
 const hasSamplingRestriction = isAnthropicModelWithSamplingRestriction(agent?.provider, agent?.modelId);

  const setSettingsEffectEvent = useEffectEvent(() => {
    setSettings({
      ...settings,
      modelSettings: { ...settings?.modelSettings, topP: undefined },
    });
  });

  const agentModelKey = agent?.provider && agent?.modelId ? `${agent?.provider}-${agent?.modelId}` : undefined;
  const topP = settings?.modelSettings?.topP;

  useEffect(() => {
    if (!agentModelKey) return;
    if (topP === undefined) return;

    setSettingsEffectEvent();
  }, [hasSamplingRestriction, agentModelKey, topP]);
```

Comment (graysonhicks) [reply packages/playground-ui/src/domains/agents/components/agent-settings.tsx]: yep, i need to get more used to useEffectEvent!

File: packages/playground-ui/src/domains/agents/components/agent-settings.tsx (hunk 3 above)
Comment (graysonhicks) [reply packages/playground-ui/src/domains/agents/components/agent-settings.tsx]: done, merci

**Review by abhiaiyer91 — APPROVED** [review]
