### PR TITLE
fix: transform LLM input/output for Braintrust Thread view

### LINKED ISSUE #9848: [BUG] Braintrust not showing data under "Thread" for a log/trace
### Describe the Bug

Braintrust has a feature where you can look at a log/trace as Trace, Timeline or Thread. Thread is convenient as it basically pretty prints the messages (role + content), however using the provided `BraintrustExporter` I don't get this data in Braintrust. Using AI SDK directly with the Braintrust wrapper I get that data.

Example of it working (using AI SDK)

Image

Compared to how it looks on Mastra's agent runs:

Image

### Steps To Reproduce

- Do a few agent runs
- Go to Braintrust and pick a "agent run.." trace
- Click Thread and see that there's no data

### Expected Behavior

_No response_

### Environment Information

_No response_

### Verification

- [x] I have searched the existing issues to make sure this is not a duplicate
- [x] I have included sufficient information for the team to reproduce and understand the issue

### PR DESCRIPTION
**Pull request by YujohnNattrass**
Fixes the Braintrust Thread view not displaying LLM messages correctly by transforming the input/output format to match Braintrust's expected format.

image

The exporter now unwraps LLM input from `{ messages: [...] }` to a direct array format, and unwraps output from `{ content: '...' }` to a direct string format. This ensures the Thread view in Braintrust displays messages properly.

Fixes #9848

## Summary by CodeRabbit

* **Bug Fixes**
  * Fixed formatting of LLM input/output for Braintrust Thread view so messages render as a direct messages array and assistant responses appear as expected.

* **Tests**
  * Updated and added tests to validate the Thread view input/output transformations and related export behavior.

* **Chores**
  * Added a changeset documenting a patch release and the formatting fix.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: observability/braintrust/src/tracing.ts [hunk 1]
```diff
@@ -365,16 +365,42 @@ export class BraintrustExporter extends BaseExporter {
...
+   */
+  private transformOutput(output: any, spanType: SpanType): any {
+    if (spanType === SpanType.MODEL_GENERATION) {
+      const { text, ...rest } = output;
+      return { role: 'assistant', content: text, ...rest };
+    }
+
+    return output;
+  }
+
```
Comment (epinzur) [inline observability/braintrust/src/tracing.ts:375]: should this also run on AGENT_RUN spans (which I think get the same inputs & outputs as MODEL_GENERATION) ?

**Review by epinzur — APPROVED** [review]
approved with one question
