### PR TITLE
Fix yarn workspace integration

### LINKED ISSUE #3458: [BUG] `mastra build` fail in yarn workspace
### Describe the Bug

I am using a monorepo and yarn's workspaces feature.
One of the packages is a Mastra project.
When trying to use `mastra build` inside the Mastra project's directory, I get an error (see below).

Adding this to the root package.json avoids the error, but it doesn't seem to me like the correct solution:

```json
  "workspaces": [
    ...
    "packages/memfault-mastra/.mastra/output",
  ]
```

### Steps To Reproduce

1. Create a new monorepo using Yarn workspaces. See [docs here](https://classic.yarnpkg.com/lang/en/docs/workspaces/#toc-how-to-use-it).
2. Initialize a new Mastra project inside the packages folder
3. Run `mastra build` in the project folder

### Expected Behavior

I would expect `mastra build` to work when using Yarn workspaces.

### Environment Information

- Mastra CLI: 0.4.4
- Node: v22.14.0
- Yarn: 4.7.0
- OS: macOS 15.3.2 (24D81)

### Component

CLI

### Code Snippet

```typescript

```

### Error Logs

```shell
$ ../../node_modules/.bin/mastra build
/Users/mthe/monorepo/packages/mastra/index.ts /Users/mthe/monorepo/packages/mastra/index.js
INFO [2025-04-05 12:06:48.136 +0200] (BUNDLER - Build): Start bundling Mastra
INFO [2025-04-05 12:06:48.138 +0200] (BUNDLER - Build): Analyzing dependencies...
INFO [2025-04-05 12:06:48.269 +0200] (BUNDLER - Build): Optimizing dependencies...
INFO [2025-04-05 12:06:50.800 +0200] (BUNDLER - Build): Bundling Mastra application
INFO [2025-04-05 12:06:51.029 +0200] (BUNDLER - Build): Bundling Mastra done
INFO [2025-04-05 12:06:51.029 +0200] (BUNDLER - Build): Copying public files
INFO [2025-04-05 12:06:51.029 +0200] (BUNDLER - Build): Done copying public files
INFO [2025-04-05 12:06:51.029 +0200] (BUNDLER - Build): Installing dependencies
Usage Error: The nearest package directory (/Users/mthe/monorepo/packages/mastra/.mastra/output) doesn't seem to be part of the project declared in /Users/mthe/monorepo.

- If /Users/mthe/monorepo isn't intended to be a project, remove any yarn.lock and/or package.json file there.
- If /Users/mthe/monorepo is intended to be a project, it might be that you forgot to list packages/mastra/.mastra/output in its workspace configuration.
- Finally, if /Users/mthe/monorepo is fine and you intend packages/mastra/.mastra/output to be treated as a completely separate project (not even a workspace), create an empty yarn.lock file in it.

$ yarn install [--json] [--immutable] [--immutable-cache] [--refresh-lockfile] [--check-cache] [--check-resolutions] [--inline-builds] [--mode #0]
INFO [2025-04-05 12:06:51.229 +0200] (BUNDLER - Build): Usage Error: The nearest package directory (/Users/mthe/monorepo/packages/mastra/.mastra/output) doesn't seem to be part of the project declared in /Users/mthe/monorepo.

- If /Users/mthe/monorepo isn't intended to be a project, remove any yarn.lock and/or package.json file there.
- If /Users/mthe/monorepo is intended to be a project, it might be that you forgot to list packages/mastra/.mastra/output in its workspace configuration.
- Finally, if /Users/mthe/monorepo is fine and you intend packages/mastra/.mastra/output to be treated as a completely separate project (not even a workspace), create an empty yarn.lock file in it.

$ yarn install [--json] [--immutable] [--immutable-cache] [--refresh-lockfile] [--check-cache] [--check-resolutions] [--inline-builds] [--mode #0]
file:///Users/mthe/monorepo/node_modules/@mastra/deployer/dist/chunk-ZAXXMFXX.js:45
            reject(new Error(`Process exited with code ${code}`));
                   ^

Error: Process exited with code 1
    at ChildProcess.<anonymous> (file:///Users/mthe/monorepo/node_modules/@mastra/deployer/dist/chunk-ZAXXMFXX.js:45:20)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1101:16)
    at ChildProcess._handle.onexit (node:internal/child_process:304:5)

Node.js v22.14.0
```

### Additional Context

_No response_

### Verification

- [x] I have searched the existing issues to make sure this is not a duplicate
- [x] I have included sufficient information for the team to reproduce and understand the issue

### PR DESCRIPTION
**Pull request by wardpeet**
## Description

Fix ignore workspaces with yarn package manager

## Related Issue(s)

Fixes #3458

## Type of Change

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Code refactoring
- [ ] Performance improvement
- [ ] Test update

## Checklist

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation (if applicable)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] I have generated a changeset for this PR

### CODE REVIEW

File: packages/deployer/src/services/deps.ts [hunk 1]
```diff
@@ -49,18 +49,18 @@ export class Deps extends MastraBase {
...
     switch (this.packageManager) {
-      case 'npm':
-        runCommand = `${this.packageManager} i`;
-        break;
       case 'pnpm':
         runCommand = `${this.packageManager} --ignore-workspace install`;
         break;
+      case 'yarn':
+        // similar to --ignore-workspace but for yarn
+        await ensureFile(path.join(dir, 'yarn.lock'));
```
Comment (TylerBarnes) [inline packages/deployer/src/services/deps.ts:61]: curious, why do we need to write it? wont yarn do this?

**Review by TylerBarnes — APPROVED** [review]

File: packages/deployer/src/services/deps.ts (hunk 1 above)
Comment (wardpeet) [reply packages/deployer/src/services/deps.ts:61]: there is a yarn.lock in the root, if we do yarn in a non-workspace folder, it crashes. Creating a new yarn.lock file, creates a new yarn root.

**Review by Covodpeter19 — COMMENTED** [review]
Ok thank u
