### PR TITLE
fix(core): preserve Date objects in tool input validation

### LINKED ISSUE #11502: [BUG] Coerced types in tool input parameters broken
### Describe the Bug

We have a tool that takes a date as input. We used to be able to do this for the input schema: 
```
z.object({ date: z.coerce.date() })
```

The model would pass an ISO string date and it would get parsed as a Javascript Date().  On beta 7 this was working. With the latest beta (19) we now get errors:

Tool input validation failed for data-warehouse-tool. Please fix the following errors and try again:\n- params.startDate: Invalid date\n- params.endDate: Invalid date

### Steps To Reproduce

Create an agent with a tool that as this input schema:

```
z.object({ date: z.coerce.date() })
```

Using beta 7, instruct the agent to call the tool with today's date. Try again with latest beta.

### Link to Minimal Reproducible Example

N/A

### Expected Behavior

Tool should accept a string date and parse it to Javascript Date().

### Environment Information

```block
System:
    OS: macOS 26.2
    CPU: (12) arm64 Apple M4 Pro
    Memory: 8.92 GB / 48.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 24.12.0 - /Users/guincho/.nvm/versions/node/v24.12.0/bin/node
    npm: 11.6.2 - /Users/guincho/.nvm/versions/node/v24.12.0/bin/npm
  Browsers:
    Chrome: 143.0.7499.170
    Safari: 26.2
  npmPackages:
    @ai-sdk/anthropic: ^2.0.56 => 2.0.56 
    @ai-sdk/openai: ^2.0.80 => 2.0.80 
    @bufbuild/protobuf: ^1.10.1 => 1.10.1 
    @connectrpc/connect: ^1.4.0 => 1.7.0 
    @connectrpc/connect-node: ^1.4.0 => 1.7.0 
    @eslint-community/eslint-plugin-eslint-comments: ^4.5.0 => 4.5.0 
    @eslint/compat: ^1.3.0 => 1.4.1 
    @eslint/eslintrc: ^3.3.1 => 3.3.1 
    @eslint/js: ^9.29.0 => 9.39.1 
    @faker-js/faker: ^9.9.0 => 9.9.0 
    @glossgenius/applications: ^11.1.2 => 11.3.0 
    @glossgenius/core-protos: ^10.317.0 => 10.329.0 
    @glossgenius/eslint-config-gg-linting: ^2.0.0 => 2.0.0 
    @glossgenius/loggers: ^9.6.0 => 9.6.0 
    @koa/router: ^13.1.0 => 13.1.1 
    @mastra/braintrust: ^1.0.0-beta.10 => 1.0.0-beta.10 
    @mastra/core: ^1.0.0-beta.19 => 1.0.0-beta.19 
    @mastra/deployer: ^1.0.0-beta.19 => 1.0.0-beta.19 
    @mastra/libsql: ^1.0.0-beta.10 => 1.0.0-beta.10 
    @mastra/loggers: ^1.0.0-beta.3 => 1.0.0-beta.3 
    @mastra/memory: ^1.0.0-beta.10 => 1.0.0-beta.10 
    @mastra/observability: ^1.0.0-beta.1 => 1.0.0-beta.9 
    @mastra/pg: ^1.0.0-beta.11 => 1.0.0-beta.11 
    @types/js-yaml: ^4.0.9 => 4.0.9 
    @types/koa: ^2.15.0 => 2.15.0 
    @types/koa__router: ^12.0.4 => 12.0.5 
    @types/node: ^24.0.4 => 24.10.1 
    @types/supertest: ^6.0.3 => 6.0.3 
    @typescript-eslint/eslint-plugin: ^8.35.0 => 8.48.0 
    @typescript-eslint/parser: ^8.35.0 => 8.48.0 
    @vitest/coverage-v8: ^2.1.8 => 2.1.9 
    @vitest/ui: ^2.1.8 => 2.1.9 
    ai: ^5.0.102 => 5.0.102 
    axios: ^1.12.0 => 1.13.2 
    braintrust: ^1.0.1 => 1.1.1 
    commander: ^14.0.1 => 14.0.2 
    dayjs: ^1.11.18 => 1.11.19 
    dd-trace: ^5.65.0 => 5.80.0 
    dotenv: ^17.2.1 => 17.2.3 
    eslint: ^9.29.0 => 9.39.1 
    eslint-import-resolver-alias: ^1.1.2 => 1.1.2 
    eslint-import-resolver-typescript: ^4.4.3 => 4.4.4 
    eslint-plugin-diff: ^2.0.3 => 2.0.3 
    eslint-plugin-functional: ^9.0.2 => 9.0.2 
    eslint-plugin-jsdoc: ^51.2.3 => 51.4.1 
    eslint-plugin-vitest: ^0.5.4 => 0.5.4 
    globals: ^16.2.0 => 16.5.0 
    graphql: ^16.9.0 => 16.12.0 
    http-graceful-shutdown: ^3.1.14 => 3.1.14 
    js-yaml: ^4.1.1 => 4.1.1 
    koa: ^3.0.3 => 3.1.1 
    lefthook: ^1.11.14 => 1.13.6 
    lockfile-lint: ^4.14.1 => 4.14.1 
    mastra: ^1.0.0-beta.12 => 1.0.0-beta.12 
    msw: ^2.12.3 => 2.12.3 
    prettier: ^3.6.0 => 3.7.4 
    supertest: ^7.1.1 => 7.1.4 
    ts-node: ^10.9.2 => 10.9.2 
    tsconfig-paths: ^4.2.0 => 4.2.0 
    tsx: ^4.21.0 => 4.21.0 
    typescript: ^5.8.3 => 5.9.3 
    vite: ^6.0.3 => 6.4.1 
    vitest: ^2.1.8 => 2.1.9 
    winston: ^3.18.3 => 3.18.3 
    zod: ^3.25.67 => 3.25.76 
  npmGlobalPackages:
    corepack: 0.34.5
    npm: 11.6.2
```

### Verification

- [x] I have searched the existing issues to make sure this is not a duplicate
- [x] I have included sufficient information for the team to reproduce and understand the issue

### PR DESCRIPTION
**Pull request by ctamulonis-glossy**
Fixes #11502

## Problem

The `convertUndefinedToNull` function in tool input validation was treating `Date` objects as plain objects and recursively processing them. Since `Date` objects have no enumerable properties, this resulted in empty objects `{}`, which broke `z.coerce.date()` validation.

This caused tools using `z.coerce.date()` schemas to fail with "Invalid date" errors when receiving date inputs from LLMs, even though the inputs were valid `Date` objects or ISO strings.

## Solution

Added checks to preserve built-in object types (Date, RegExp, Error) before recursive processing in `convertUndefinedToNull`. This ensures that:
- `Date` objects are passed through unchanged to Zod validation
- `z.coerce.date()` can properly validate and coerce both Date objects and ISO strings
- Other built-in types are also preserved correctly

## Changes

- Modified `convertUndefinedToNull` in `packages/core/src/tools/validation.ts` to check for and preserve built-in object types
- Added 8 comprehensive tests in `packages/core/src/tools/validation.test.ts` covering:
  - Date object preservation with `z.coerce.date()`
  - ISO string to Date coercion
  - Nested structures with dates
  - Optional date fields
  - RegExp and Error object preservation
  - Date objects in arrays
  - Mixed Date objects and ISO strings
- Added changeset for release notes

## Testing

All new tests pass:
```
✓ should preserve Date objects when validating z.coerce.date() schemas
✓ should handle ISO string dates with z.coerce.date()
✓ should preserve Date objects in nested structures
✓ should preserve Date objects with optional fields
✓ should preserve RegExp objects
✓ should preserve Error objects
✓ should handle Date objects in arrays
✓ should handle mixed Date objects and ISO strings
```

Tested end-to-end with real tools using `z.coerce.date()` parameters.

## Summary by CodeRabbit

* **Bug Fixes**
  * Tool input validation now preserves non-plain objects (e.g., Date, RegExp, Error, Map, Set, URL, class instances), preventing them from becoming empty objects and allowing Date objects and ISO date strings to validate correctly.

* **Tests**
  * Added comprehensive tests covering preservation of built-in and custom object types across nested structures, arrays, optional/nullable fields, and mixed inputs.

* **Chores**
  * Added changelog entry and bumped patch version.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: packages/core/src/tools/validation.ts [hunk 1]
```diff
@@ -116,7 +116,13 @@ function convertUndefinedToNull(input: unknown): unknown {
     return input.map(convertUndefinedToNull);
   }
 
-  // It's an object - recursively process all properties
+  // Preserve built-in object types that should not be recursively processed
+  // (Date, RegExp, Error, etc.) - fixes #11502
+  if (input instanceof Date || input instanceof RegExp || input instanceof Error) {
```
Comment (intojhanurag) [inline packages/core/src/tools/validation.ts]: One thought on this, instead of whitelisting a few built-ins, would it make sense to only recurse into plain objects?
That way other non-JSON objects (e.g. Map, URL, class instances) won’t accidentally get flattened if they ever show up in tool inputs.
let suppose this type of input :
```typescript
const input = {
  startDate: new Date(),
  metadata: new Map([['agent', 'planner']]),
  url: new URL('https://example.com')
};
````
Correct me if i am wrong.

Comment (ctamulonis-glossy) [reply packages/core/src/tools/validation.ts]: Done! Sorry for the delay, for some reason I didn't get notified for your original comment.

**Review by epinzur — APPROVED** [review]
Looks great! Thanks for this contribution!
