### PR TITLE
fix(cli): properly set base url in playground

### LINKED ISSUE #6623: Wrong MCP Server SSE/HTTP Urls inside Playground when port is changed
Issue Description:
I updated the default mastra port from 4111 to 3000. The Playground document does not update the URLs for MCP Server's SSE & HTTP urls. Kindly refer the screenshot

Screenshot:

Image

### PR DESCRIPTION
**Pull request by DanielSLew**
## Description

We weren't handling the case in the playground where a user sets a host or a port. We'd always default the default port and host.

Also fixes https://github.com/mastra-ai/mastra/issues/6623

## Type of Change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Code refactoring
- [ ] Performance improvement
- [ ] Test update

## Checklist

- [ ] I have made corresponding changes to the documentation (if applicable)
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: packages/cli/src/commands/dev/dev.ts [hunk 1]
```diff
@@ -186,30 +186,34 @@ export async function dev({
...
     portToUse = String(
       await getPort({
         port: portList,
       }),
     );
   }
 
+  // Set environment variables for playground development
+  process.env.MASTRA_DEV_PORT = portToUse.toString();
+  process.env.MASTRA_DEV_HOST = serverOptions?.host ?? 'localhost';
```
Comment (wardpeet) [inline packages/cli/src/commands/dev/dev.ts]: This doesn't do anything as the playground is prebundled. Also let's not add global env vars here, we spawn a node server which should be used instead

```suggestion
```

File: packages/cli/src/playground/vite.config.ts [hunk 2]
```diff
@@ -27,13 +27,17 @@ export default defineConfig(({ mode }) => {
   };
 
   if (mode === 'development') {
+    // Use environment variable for the target port, fallback to 4111
+    const targetPort = process.env.MASTRA_DEV_PORT || '4111';
```
Comment (wardpeet) [inline packages/cli/src/playground/vite.config.ts]: This is fine for monorepo testing I guess, but it's not used when using mastra dev

File: packages/cli/src/commands/dev/dev.ts (hunk 1 above)
Comment (DanielSLew) [reply packages/cli/src/commands/dev/dev.ts]: fixed it!

File: packages/cli/src/playground/vite.config.ts (hunk 2 above)
Comment (DanielSLew) [reply packages/cli/src/playground/vite.config.ts]: yeah, this is mainly just for developing in the playground if we use a diff port

**Review by wardpeet — APPROVED** [review]
