### PR TITLE
Bug/dirty telemetry attributes

### LINKED ISSUE #5870: [BUG] telemetry attributes is reported as promise status description when call agent stream method
### Describe the Bug

I found mastra will report dirty attributes when `stream` method was called on agent object. When I switched to `generate` method, it was normal.
The attributes reported by stream method:

```yaml
componentName: My Agent
lmnr.span.path:
  - agent.stream
lmnr.span.ids_path: []
agent.stream.result: '{"warningsPromise":{"status":{"type":"pending"}},"usagePromise":{"status":{"type":"pending"}},"finishReasonPromise":{"status":{"type":"pending"}},"providerMetadataPromise":{"status":{"type":"pending"}},"textPromise":{"status":{"type":"pending"}},"reasoningPromise":{"status":{"type":"pending"}},"reasoningDetailsPromise":{"status":{"type":"pending"}},"sourcesPromise":{"status":{"type":"pending"}},"filesPromise":{"status":{"type":"pending"}},"toolCallsPromise":{"status":{"type":"pending"}},"toolResultsPromise":{"status":{"type":"pending"}},"requestPromise":{"status":{"type":"pending"}},"responsePromise":{"status":{"type":"pending"}},"stepsPromise":{"status":{"type":"pending"}},"baseStream":{}}'
agent.stream.argument.0: '[{"role":"user","content":"你是谁？"}]'
```

The attributes reported by generate method:

```yaml
componentName: My Agent
lmnr.span.path:
  - agent.generate
lmnr.span.ids_path: []
agent.generate.result: '{"text":"我是豆包，是由字节跳动研发的人工智能。我可以陪你畅快聊天，为你解答各种问题，无论是知识科普、生活建议，还是文本创作等，有什么需求都能跟我说一说。
  ","files":[],"reasoningDetails":[],"toolCalls":[],"toolResults":[],"finishReason":"stop","usage":{"promptTokens":21,"completionTokens":48,"totalTokens":69},"warnings":[],"request":{"body":"{\"model\":\"ep-20250206110029-vmn8r\",\"temperature\":0,\"messages\":[{\"role\":\"system\",\"content\":\"You
  are a helpful
  assistant.\"},{\"role\":\"user\",\"content\":\"你是谁？\"}]}"},"response":{"id":"021752309663173993d717f33c8850963d84c7a3d1278ee18760e","timestamp":"2025-07-12T08:41:04.000Z","modelId":"doubao-1-5-pro-32k-250115","headers":{"content-length":"660","content-type":"application/json;
  charset=utf-8","date":"Sat, 12 Jul 2025 08:41:03
  GMT","server":"istio-envoy","x-client-request-id":"unknown-20250712164103-PeeskYPE","x-envoy-upstream-service-time":"1336","x-request-id":"021752309663173993d717f33c8850963d84c7a3d1278ee18760e"},"body":{"choices":[{"finish_reason":"stop","index":0,"logprobs":null,"message":{"content":"我是豆包，是由字节跳动研发的人工智能。我可以陪你畅快聊天，为你解答各种问题，无论是知识科普、生活建议，还是文本创作等，有什么需求都能跟我说一说。
  ","role":"assistant"}}],"created":1752309664,"id":"021752309663173993d717f33c8850963d84c7a3d1278ee18760e","model":"doubao-1-5-pro-32k-250115","service_tier":"default","object":"chat.completion","usage":{"completion_tokens":48,"prompt_tokens":21,"total_tokens":69,"prompt_tokens_details":{"cached_tokens":0},"completion_tokens_details":{"reasoning_tokens":0}}},"messages":[{"role":"assistant","content":[{"type":"text","text":"我是豆包，是由字节跳动研发的人工智能。我可以陪你畅快聊天，为你解答各种问题，无论是知识科普、生活建议，还是文本创作等，有什么需求都能跟我说一说。
  "}],"id":"msg-OgmQGOD1hAAW49mvlwUKyKKF"}]},"steps":[{"stepType":"initial","text":"我是豆包，是由字节跳动研发的人工智能。我可以陪你畅快聊天，为你解答各种问题，无论是知识科普、生活建议，还是文本创作等，有什么需求都能跟我说一说。
  ","reasoningDetails":[],"files":[],"sources":[],"toolCalls":[],"toolResults":[],"finishReason":"stop","usage":{"promptTokens":21,"completionTokens":48,"totalTokens":69},"warnings":[],"request":{"body":"{\"model\":\"ep-20250206110029-vmn8r\",\"temperature\":0,\"messages\":[{\"role\":\"system\",\"content\":\"You
  are a helpful
  assistant.\"},{\"role\":\"user\",\"content\":\"你是谁？\"}]}"},"response":{"id":"021752309663173993d717f33c8850963d84c7a3d1278ee18760e","timestamp":"2025-07-12T08:41:04.000Z","modelId":"doubao-1-5-pro-32k-250115","headers":{"content-length":"660","content-type":"application/json;
  charset=utf-8","date":"Sat, 12 Jul 2025 08:41:03
  GMT","server":"istio-envoy","x-client-request-id":"unknown-20250712164103-PeeskYPE","x-envoy-upstream-service-time":"1336","x-request-id":"021752309663173993d717f33c8850963d84c7a3d1278ee18760e"},"body":{"choices":[{"finish_reason":"stop","index":0,"logprobs":null,"message":{"content":"我是豆包，是由字节跳动研发的人工智能。我可以陪你畅快聊天，为你解答各种问题，无论是知识科普、生活建议，还是文本创作等，有什么需求都能跟我说一说。
  ","role":"assistant"}}],"created":1752309664,"id":"021752309663173993d717f33c8850963d84c7a3d1278ee18760e","model":"doubao-1-5-pro-32k-250115","service_tier":"default","object":"chat.completion","usage":{"completion_tokens":48,"prompt_tokens":21,"total_tokens":69,"prompt_tokens_details":{"cached_tokens":0},"completion_tokens_details":{"reasoning_tokens":0}}},"messages":[{"role":"assistant","content":[{"type":"text","text":"我是豆包，是由字节跳动研发的人工智能。我可以陪你畅快聊天，为你解答各种问题，无论是知识科普、生活建议，还是文本创作等，有什么需求都能跟我说一说。
  "}],"id":"msg-OgmQGOD1hAAW49mvlwUKyKKF"}]},"providerMetadata":{"openai":{"reasoningTokens":0,"cachedPromptTokens":0}},"experimental_providerMetadata":{"openai":{"reasoningTokens":0,"cachedPromptTokens":0}},"isContinued":false}],"experimental_providerMetadata":{"openai":{"reasoningTokens":0,"cachedPromptTokens":0}},"providerMetadata":{"openai":{"reasoningTokens":0,"cachedPromptTokens":0}},"sources":[]}'
agent.generate.argument.0: '[{"role":"user","content":"你是谁？"}]'
```

### Steps To Reproduce

I use nestjs as my http server. The controller code as follows:

```typescript
@Controller('agent')
export class AgentController {
  @Get('ask')
  public async askStreamed(@Query('q') q: string) {
    const stream = await mastra.getAgent('myAgent').stream([
      {
        role: 'user',
        content: q,
      },
    ])

    const readable = Readable.from(stream.textStream)
    return new StreamableFile(readable)
  }

  @Get('ask-blocked')
  public async askBlocked(@Query('q') q: string) {
    const result = await mastra.getAgent('myAgent').generate([
      {
        role: 'user',
        content: q,
      },
    ])
    return result.text
  }
}
```

### Expected Behavior

_No response_

### Environment Information

- Mastra version 0.10.12
- Node version 22.15.0
- OS version win11
- I use laminar as my tracing provider.

### Verification

- [x] I have searched the existing issues to make sure this is not a duplicate
- [x] I have included sufficient information for the team to reproduce and understand the issue

### PR DESCRIPTION
**Pull request by nickperry12**
## Description
- Added a function that intercepts the `onFinish` callback to capture telemetry data when streams complete
- Streams return immediately while telemetry is captured asynchronously on completion
- This fix works for both `agent.stream()` and `agent.streamVNext()`
- Existing behaviours are preserved for backwards compatibility

## Related Issue(s)

Fixes #5870

## Type of Change

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Code refactoring
- [ ] Performance improvement
- [ ] Test update

## Checklist

- [ ] I have made corresponding changes to the documentation (if applicable)
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: packages/core/src/telemetry/telemetry.decorators.ts [hunk 1]
```diff
@@ -56,51 +145,63 @@ export function withSpan(options: {
...
+            'http.request_id': { value: requestId ?? '' },
           }),
         );
       }
 
-      let result;
+      let result: unknown;
       try {
+        // For streaming methods, enhance arguments with telemetry capture before calling
+        const enhancedArgs = isStreamingResult(result, methodName)
```
[the remark this answers is not in the document]
Comment (nickperry12) [reply packages/core/src/telemetry/telemetry.decorators.ts:182]: @greptileai I think there's a misunderstanding. The method won't return false here, as the first check is for the method name, and returns true immediately if there are method name matches for known streaming methods

**Review by wardpeet — COMMENTED** [review]
The actual implementation looks good but what I would do to improve the readability of this PR is to add `stream` to the exclude list inside the agent class.

```
@InstrumentClass({
  prefix: 'agent',
  excludeMethods: [
    'hasOwnMemory',
    'getMemory',
    '__primitive',
    '__registerMastra',
    '__registerPrimitives',
    '__setTools',
    '__setLogger',
    '__setTelemetry',
    'stream',
    'log',
    'getModel',
    'getInstructions',
    'getTools',
    'getLLM',
    'getWorkflows',
    'getDefaultGenerateOptions',
    'getDefaultStreamOptions',
    'getDescription',
  ],
})
```

Inside the stream i would manually call the withSpan  or duplicate the logic so it's nicely inside the caller function. This improves readabilty but also awareness that we should check any stream call that the telemetry is updated correctly

**Comment by nickperry12** [comment]
@wardpeet this is what I ended up doing, basically wrapping the pre-existing logic inside of the `stream` and `streamVNext` methods within a span decorator. Is this in-line with what you were thinking? 

```
    // Manual telemetry span setup for streaming
    const spanDecorator = withSpan({
      spanName: 'agent.stream',
      skipIfNoTelemetry: true,
      tracerName: 'default-tracer',
    });

    const wrappedStream = spanDecorator(
      this,
      'stream',
      {
        value: async (
          messages: string | string[] | CoreMessage[] | AiMessageType[] | UIMessageWithMetadata[],
          streamOptions: AgentStreamOptions<OUTPUT, EXPERIMENTAL_OUTPUT> = {},
        ) => {
          const defaultStreamOptions = await this.getDefaultStreamOptions({ runtimeContext: streamOptions.runtimeContext });

          const mergedStreamOptions: AgentStreamOptions<OUTPUT, EXPERIMENTAL_OUTPUT> = {
            ...defaultStreamOptions,
            ...streamOptions,
          };

          const { llm, before, after } = await this.prepareLLMOptions(messages, mergedStreamOptions);
          const { onFinish, runId, output, experimental_output, ...llmOptions } = await before();

          if (!output || experimental_output) {
            this.logger.debug(`Starting agent ${this.name} llm stream call`, {
              runId,
            });

            const streamResult = llm.__stream({
              ...llmOptions,
              onFinish: async result => {
                try {
                  const outputText = result.text;
                  await after({
                    result,
                    outputText,
                  });
                } catch (e) {
                  this.logger.error('Error saving memory on finish', {
                    error: e,
                    runId,
                  });
                }
                await onFinish?.({ ...result, runId } as any);
              },
              runId,
              experimental_output,
            });

            return streamResult as
              | StreamTextResult<any, OUTPUT extends ZodSchema ? z.infer<OUTPUT> : unknown>
              | StreamObjectResult<any, OUTPUT extends ZodSchema ? z.infer<OUTPUT> : unknown, any>;
          }

          this.logger.debug(`Starting agent ${this.name} llm streamObject call`, {
            runId,
          });

          return llm.__streamObject({
            ...llmOptions,
            onFinish: async result => {
              try {
                const outputText = JSON.stringify(result.object);
                await after({
                  result,
                  outputText,
                  structuredOutput: true,
                });
              } catch (e) {
                this.logger.error('Error saving memory on finish', {
                  error: e,
                  runId,
                });
              }
              await onFinish?.({ ...result, runId } as any);
            },
            runId,
            structuredOutput: output,
          });
        },
      } as PropertyDescriptor,
    );

    // Call the wrapped method
    return (wrappedStream?.value as any).call(this, messages, streamOptions);
    ```

**Comment by wardpeet** [comment]
@nickperry12 yes, seems like it. if you can make sure to put the custom promise pieces here instead of the decorator itself

File: packages/core/src/telemetry/telemetry.ts [hunk 2]
```diff
@@ -170,6 +170,7 @@ export class Telemetry {
       const span = this.tracer.startSpan(context.spanName);
 
       function handleError(error: unknown) {
+        debugger;
```
Comment (DanielSLew) [inline packages/core/src/telemetry/telemetry.ts]:
```suggestion
```

File: packages/core/src/telemetry/telemetry.decorators.ts [hunk 3]
```diff
@@ -56,56 +143,69 @@ export function withSpan(options: {
...
+            span.setAttribute(`${spanName}.result`, JSON.stringify(result));
+          } catch {
+            span.setAttribute(`${spanName}.result`, '[Not Serializable]');
+          }
         }
 
         // Return regular results
         return result;
       } catch (error) {
+        debugger;
```
Comment (DanielSLew) [inline packages/core/src/telemetry/telemetry.decorators.ts]:
```suggestion
```

**Review by DanielSLew — APPROVED** [review]

**Comment by wardpeet** [comment]
@DanielSLew this change https://github.com/mastra-ai/mastra/pull/6265#issuecomment-3133492550 should still happen

**Review by DanielSLew — APPROVED** [review]
